package roles

import (
	"bytes"
	"fmt"
	"strings"
)

// RenderCodexAgentFiles renders every role in roleList into codex's
// step-<role>.toml content, keyed by output file name ("step-executor.toml",
// ...). resolvedModels supplies the model slug to declare per role name --
// already validated against the machine's codex model catalog by the caller
// (internal/cli/roles_generate.go's CatalogProbe, aihub#642 AC6); this
// function never probes a catalog itself. A role absent from resolvedModels
// (or mapped to "") gets no `model` key at all -- the omit-and-warn fallback
// shape (AC7); the caller is responsible for having already emitted the
// non-suppressible warning before calling this with an empty model.
//
// aihub#655 correction: aihub#642 shipped this with `name`, `description`,
// and `instructions` keys, and shipped it reporting success with no proof
// codex could actually load the result -- it could not, in two different and
// differently-dangerous ways, both live-verified against codex-cli 0.154.0:
// `name` and `description` are rejected as unknown fields under EVERY tested
// loading path (a loud, `--strict-config` file:line:col error) -- but
// `instructions` is worse than rejected: it is silently ACCEPTED by
// --strict-config (no error at all) and then never reaches the model's
// prompt (`codex debug prompt-input` marker-count testing: 0 occurrences for
// `instructions`, 1 for `developer_instructions`, same marker text). A parser
// that takes the field and drops it on the floor is exactly the "ships,
// reports success, silently unloadable" failure mode this wi exists to
// close -- worse than a field it refuses outright, since nothing ever
// surfaces the mistake. `developer_instructions` is the one prompt-body key
// confirmed to actually reach the model. This function keeps its exact name,
// signature, and "step-<role>.toml" filename -- both pinned by
// internal/cli/roles_generate_test.go, which this wi's declared_resources do
// not allow editing -- but its field shape now matches what codex's own
// --strict-config parser actually accepts AND actually delivers. This is NOT
// the file codex loads today, though: its only caller is
// internal/cli.generateRoles (cmd/polyforge/main.go no longer calls this
// function at all -- see its generateCodexProfiles instead), which writes it
// into .codex-plugin/agents/, a directory codex never scans (no such
// auto-discovery mechanism exists in this codex version at all -- see
// RenderCodexProfiles below for the actually-loadable path).
func RenderCodexAgentFiles(roleList []Role, resolvedModels map[string]string) (map[string]string, error) {
	return renderCodexTOML(roleList, resolvedModels, ".toml")
}

// RenderCodexProfiles renders every role in roleList into a codex CONFIG
// PROFILE file, keyed by output file name ("step-executor.config.toml",
// ...). The ".config.toml" suffix is not a style choice: it is the literal
// filename codex's `-p <name>` / `--profile <name>` flag requires -- codex's
// own error for the legacy top-level `profile = "..."` config key says so
// verbatim ("use `--profile myprofile` with `myprofile.config.toml`
// instead"), and codex's own error for the current key resolves the file
// against $CODEX_HOME (default ~/.codex), not any plugin- or
// project-relative directory. codex has no subagent-file auto-discovery
// mechanism in this version at all (aihub#655 investigation superseding an
// aihub#642 doc comment that claimed one existed); a profile file loaded via
// `-p`/`--profile` is the one mechanism live-verified, this session, to
// actually work.
//
// Same three fields as RenderCodexAgentFiles, same reason: `model`,
// `sandbox_mode`, `developer_instructions` are the only keys
// `codex exec --strict-config -p <name>` accepts from a profile file;
// `name` and `description` are never written.
func RenderCodexProfiles(roleList []Role, resolvedModels map[string]string) (map[string]string, error) {
	return renderCodexTOML(roleList, resolvedModels, ".config.toml")
}

// renderCodexTOML is the shared body behind RenderCodexAgentFiles and
// RenderCodexProfiles -- the two differ only in output filename, never in
// field shape, so both stay identical by construction instead of by
// discipline.
// The agent NAME half of the output filename comes from dispatch.go (one copy for all
// four harnesses); filenameSuffix is only the extension that distinguishes an agent file
// from a config profile.
func renderCodexTOML(roleList []Role, resolvedModels map[string]string, filenameSuffix string) (map[string]string, error) {
	out := make(map[string]string, len(roleList))
	for _, r := range roleList {
		shape, err := CompileCapability(r.Capability.ReadOnly, "codex")
		if err != nil {
			return nil, fmt.Errorf("role %q: %w", r.Name, err)
		}

		var b bytes.Buffer
		b.WriteString("# Generated by polyforge -- do not edit by hand.\n")
		b.WriteString("# Regenerated the next time whatever produced this file runs again; local edits are silently overwritten.\n")
		if model := resolvedModels[r.Name]; model != "" {
			fmt.Fprintf(&b, "model = %s\n", tomlQuoted(model))
		}
		if shape.CodexSandboxMode != "" {
			fmt.Fprintf(&b, "sandbox_mode = %s\n", tomlQuoted(shape.CodexSandboxMode))
		}
		fmt.Fprintf(&b, "developer_instructions = %s\n", tomlTripleQuoted(r.Prompt))

		out[mustAgentName("codex", r.Name)+filenameSuffix] = b.String()
	}
	return out, nil
}

// tomlQuoted renders s as a TOML basic string. Role names/descriptions are
// short ASCII prose with no embedded quotes or control characters today, so
// Go's %q is a correct TOML basic string in practice; this helper exists so
// the two escaping conventions (single-line vs triple-quoted) are named
// distinctly at each call site. Not a general-purpose TOML string encoder --
// if a future role definition's prose needs real escaping, this is the place
// to add it.
func tomlQuoted(s string) string {
	return fmt.Sprintf("%q", s)
}

// tomlTripleQuoted renders s as a TOML multi-line basic string. Every
// committed role prompt today is plain markdown prose with no embedded `"""`
// sequence, so no escaping beyond the delimiters is done; a prompt that ever
// contained one would produce invalid TOML, same caveat as tomlQuoted above.
func tomlTripleQuoted(s string) string {
	var b strings.Builder
	b.WriteString(`"""` + "\n")
	b.WriteString(s)
	if !strings.HasSuffix(s, "\n") {
		b.WriteString("\n")
	}
	b.WriteString(`"""`)
	return b.String()
}
