package mcp_test

// aihub#482 — K10, the contract-card arm that reads a LIVE response.
//
// ─── The hole this closes, as measured ──────────────────────────────────────
//
// contract_cards_gate_test.go's K7 compares a card's `response_keys_observed`
// against docs/audits/aihub-412-corpus-facts/response-keys/<tool>.json. BOTH
// SIDES ARE CHECKED-IN FILES. Probed on origin/main = 6bd9d80 and reproduced on
// 0dca671: dropping `role` from pf_whoami.md AND from its corpus record leaves
// the whole card gate green, while the live tool still hands `role` to every
// caller. aihub#473 added the two arms that bound that (CORPUS_NULL_MASKS_RECORD
// and K8 FLOOR_CORPUS) and neither closes it, because neither reaches a server.
//
// This file is the arm that does: it drives the published tools against a real
// Postgres, a real router, the real pkg/client and the real MCP transport, and
// holds what comes back against what the cards declare.
//
// ─── RATCHET, not EQUALITY — and the corpus stated the ratchet backwards ────
//
// The corpus records' `purpose` field used to read "A later projection may not
// drop a key on this list without a deliberate decision". Two things are wrong
// with using that as the specification, and both are measurements from this
// walk rather than opinions:
//
//  1. EQUALITY (the card list is exactly the live keys) is refused by the data.
//     A corpus record is a UNION over hundreds of calls with different
//     arguments; one live call reaches one branch. Measured 2026-09-08,
//     card-side keys no single live call produced: pf_recall's `next_cursor`,
//     `request_adjusted` and `unmatched_types` (a short unfiltered recall pages
//     once, adjusts nothing and matches every type); pf_claim_work_item's
//     `worktrees` and `unrecognized_resources` (a project with no repos and a
//     clean declaration); pf_get_memory's `emb_dims`, `emb_model`, `expires_at`,
//     `last_activated_at`, `last_activated_by`, `rendered_html` and
//     `work_item_id`. Enforcing equality would mean deleting from the cards keys
//     real callers have really been handed. So equality is not a stricter
//     version of this test — it is a WRONGER one.
//
//  2. The ratchet as the corpus WORDED it is unenforceable for the same reason:
//     "a key on this list must still be present" is false of every conditional
//     key above on any given call, so honouring it would require driving every
//     branch of every tool. This walk does not, and a gate that claims coverage
//     it does not have is the failure this whole card set exists to avoid.
//
// ⇒ The enforceable statement, and the one that closes the measured hole, is the
// CONVERSE ratchet: **every top-level key a live response actually carries must
// be declared** — the declared set may never shrink below what the server emits.
// Additions to the declaration stay cheap (that is what makes it a ratchet and
// not equality); additions to the LIVE side cost a committed, reviewed edit.
// Under it, dropping `role` from pf_whoami's card and record reddens here,
// because the live server still emits `role`. docs/mcp-cards/README.md and the
// corpus records' `purpose` field say the same thing in the same direction; if
// you change one, change all three.
//
// ─── Where "declared" lives, and why it is two files ────────────────────────
//
// A live key counts as declared if the card's `response_keys_observed` names it
// OR docs/mcp-cards/live-response-keys.json does. The second file is not an
// escape hatch bolted on afterwards — it is forced by K7's own rules. K7
// CORPUS_INVENTED refuses a card that lists a key aihub#412's corpus has no
// record of, and the corpus is GENERATED by scripts/pf_corpus_extract.py from
// transcripts, so a key that entered the server after the corpus window CANNOT
// be added to a card without hand-editing a generated file (which
// docs/audits/aihub-412-corpus-facts/README.md forbids in as many words).
// live-response-keys.json is where those keys are declared instead, with the
// reason each one is not in the corpus.
//
// 🔴 It is checked by EQUALITY against `live \ card`, not as a permission list,
// and that is the whole reason it is safe to have. A permission list only ever
// grows: entries stay after the card catches up, and the ceiling on it stops
// meaning anything. Equality makes the file self-cleaning in all four
// directions — an undeclared live key reddens, an invented entry reddens, an
// entry the card has since absorbed reddens as stale, and a key the server
// stops emitting reddens too.
//
// ─── The layer: the whole stack, because a thinner one cannot answer this ───
//
// newE2EStack (wi_echo_e2e_db_test.go) is reused verbatim: migrated Postgres,
// server.NewRouter in-process over httptest, pkg/client, mcp.New and a real SDK
// session over an in-memory transport. Nothing thinner is admissible. Calling
// the handlers directly would skip the response PROJECTIONS
// (claim_response_slim.go, force_takeover_response_slim.go, recall_slim.go,
// list_wi_slim.go) — and every key this walk found undeclared today came from a
// projection change, so a handler-level walk would have reported green on
// exactly the population it exists to measure. A fake server is worse still: it
// would make this file a mirror of the fixture, which is the copy-to-copy
// failure it was written to end.
//
// ─── What it cannot reach: nothing, since aihub#501 ─────────────────────────
//
// Six tools used to need a git worktree and a GitHub remote — pf_commit,
// pf_diff, pf_pr, pf_push, pf_ship, pf_wrap — and were named in
// liveWalkOutOfReach with the reason. aihub#501 built the fixture they wanted
// (a bare repo as origin, a clone as the worktree, both under t.TempDir(), and
// a stub `gh` whose field set is derived from the flag aihub passes it) and
// folded them into this same walk; card_response_keys_live_git_e2e_db_test.go
// holds that half and states exactly which layer of each is live and which is
// qualified. liveWalkOutOfReach is now EMPTY, and the arm that reads it still
// fails if a tool joins it, so shrinking the walk is not a silent option.
//
// ─── Running it ─────────────────────────────────────────────────────────────
//
//	AIHUB_TEST_DB='postgres://postgres:test@127.0.0.1:5433/aihub_test?sslmode=disable' \
//	  go test ./internal/mcp/ -run TestE2ELiveResponseKeys -count=1 -v
//
// Rewrite the golden file after a deliberate response change (then write the
// reason for each new entry by hand — the regen leaves a placeholder the gate
// rejects):
//
//	AIHUB_TEST_DB=... PF_LIVE_KEYS_REGEN=1 go test ./internal/mcp/ -run TestE2ELiveResponseKeys
//
// The DB must already be migrated; like newE2EStack this test connects, it does
// not migrate. Registered in internal/citest/dbtestcov/gated_tests.txt and run
// by ci.yml's "aihub#482 live response-key contract DB tests" step.

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"
)

// liveKeysFileRel is the golden file: per tool, the top-level keys a live
// response carries that the card's `response_keys_observed` does not name, each
// with the reason it is not in aihub#412's corpus.
const liveKeysFileRel = "docs/mcp-cards/live-response-keys.json"

// floorLiveTools bounds how many tools the walk actually observed a JSON object
// result from. Same reason every floor in contract_cards_gate_test.go exists: a
// walk that drove nothing would satisfy every per-tool arm below by having
// nothing to quantify over. Measured 2026-09-08: 39 of the 45 published tools.
// Measured 2026-09-09 after aihub#501 added the git arm: 44 — all 45 minus
// pf_diff, whose result is prose and so contributes no keys (liveWalkProseOnly).
//
// The headroom is kept at the 5 it was set with, deliberately, rather than
// tightened to make a total loss of the git arm trip this. That loss is already
// named tool-by-tool by REACH_GAP and GIT_WALK_GAP below, which cannot be
// satisfied vacuously; a floor duplicating them would only add a second number
// to update.
const floorLiveTools = 39

// floorLiveKeyChecks bounds the (tool, key) pairs the walk confirmed declared —
// on the card or, for the entries listed below, in the golden file. floorLiveTools
// alone is satisfied by 44 tools that each answer `{}`; this is the arm that says
// the responses had content. Measured 2026-09-08: 247. Measured 2026-09-09 with
// the git arm: 284 on a freshly migrated database, which is what CI runs against
// and what it stayed at over repeated runs against that same database, and 285 on
// one that had already served about twenty runs of this suite. That ±1 is not new
// and is not the git arm's: the same drift was measured on the base walk before
// aihub#501 (248 fresh, 249 on the long-lived database), so it lives somewhere in
// the 39 tools runLiveKeyWalk drives. Which one is unconfirmed; it is left alone
// because the floor keeps the ~77% ratio the first one was set at and clears both
// values by ~65, and because it is a fact about the fixture rather than about a
// contract. The unconditional non-JSON log at the end of the test is there so a
// future move in this number can be attributed instead of guessed at.
const floorLiveKeyChecks = 218

// maxUndeclaredLiveKeys is a CEILING ON DEBT, not a floor on a measurement, so
// like maxPendingCards it IS set at the measured value on purpose. Every entry
// is a key a caller receives that the tool's card does not name; the card is
// where a reader looks, so each one is a small documentation debt. Lowering it
// happens for free when the corpus is re-extracted and the cards absorb the key;
// raising it costs an edit here that somebody signs. Retiring a tool lowers it the
// same way: aihub#446 took it 16 -> 13 by removing pf_adopt/close/ignore_artifact,
// whose one entry each was the whole of their response. Measured 2026-09-08: 13.
//
// 13 -> 14 on 2026-09-09: aihub#501 gave the six git-dependent tools a live arm
// and the first thing it found was pf_wrap's `pushed_sha`, a key callers have been
// handed since 2026-08-14 that no card names. That is the debt this ceiling
// counts, and the point of the arm is that it is now counted rather than
// invisible; the entry in the golden file carries the derivation.
//
// 14 -> 16 on 2026-09-12: aihub#360 added the `lexical` section to pf_recall
// and pf_list_work_items. The two keys are declared in the golden file because
// K7 CORPUS_INVENTED forbids a card from naming a key the generated corpus has
// no record of, and the corpus predates the section; they move onto the cards
// whenever the corpus is next re-extracted, which lowers this back for free.
const maxUndeclaredLiveKeys = 16

// liveWalkOutOfReach names the published tools this walk cannot drive, with the
// reason. It is asserted to be EXACTLY the set of undriven tools, so a tool that
// silently stops being driven fails K10 rather than quietly shrinking the walk.
//
// 🔴 IT IS EMPTY, AND THE EMPTINESS IS THE POINT — every published tool is now
// driven against a live response. It held six entries until aihub#501
// (pf_commit, pf_diff, pf_pr, pf_push, pf_ship, pf_wrap), all of them wanting a
// git worktree and a remote, and card_response_keys_live_git_e2e_db_test.go
// builds both. The map stays because it is the declared escape hatch: a tool
// that genuinely cannot be driven belongs here WITH ITS REASON rather than
// silently absent, and REACH_GAP below is what forces that choice to be made in
// a reviewed edit. Deleting the map would make "not driven" expressible by doing
// nothing.
var liveWalkOutOfReach = map[string]string{}

// liveWalkProseOnly names the tools the walk DOES drive but whose successful
// result is not a JSON object, so they contribute no top-level keys.
//
// This is a different claim from liveWalkOutOfReach's and must not be collapsed
// into it. "Cannot be driven" is a gap in the walk; "carries no keys" is a fact
// about the tool, and it is the same fact the aihub#412 corpus records state of
// their own empty lists ("not measurable this way", not "returns nothing"). Each
// entry is held three ways by the arm below — the walk really drove the tool, the
// result really was not JSON, and the card really claims no keys — so an entry
// here cannot be used to excuse a tool whose keys stopped being checked.
var liveWalkProseOnly = map[string]string{
	"pf_diff": "the whole result is a raw unified diff, so there are no top-level keys; " +
		"its card lists none and the walk asserts the diff names the file it changed",
}

// ─────────────────────────────── the walk ────────────────────────────────────

// liveKeyWalk records the union of top-level keys each tool returned, built the
// way the aihub#412 extractor built its records: successful strict-JSON object
// results only.
type liveKeyWalk struct {
	s        *e2eStack
	observed map[string]map[string]bool
	// prose records tools whose call SUCCEEDED but whose result is not a JSON
	// object, so there are no top-level keys to compare. It is separate from
	// failed because the two are different facts and only one of them is a
	// problem: a refusal means the walk could not drive the tool, while prose
	// means it drove it and the tool has no key surface. Before aihub#501 the
	// distinction did not exist, so pf_diff — whose whole result is a raw diff —
	// could only have been recorded as a failure.
	prose  map[string]bool
	failed map[string][]string
}

func newLiveKeyWalk(s *e2eStack) *liveKeyWalk {
	return &liveKeyWalk{
		s:        s,
		observed: map[string]map[string]bool{},
		prose:    map[string]bool{},
		failed:   map[string][]string{},
	}
}

// drive calls one tool and folds its top-level keys into the union.
func (w *liveKeyWalk) drive(t *testing.T, tool string, args map[string]any) map[string]any {
	t.Helper()
	_, decoded := w.driveResult(t, tool, args)
	return decoded
}

// driveResult is drive with the raw result text handed back as well, for the one
// caller that needs it: a tool whose result is prose decodes to no keys, so the
// text is the only evidence that the call did anything (see runLiveGitKeyWalk's
// pf_diff row).
//
// A refusal is RECORDED rather than fatal, and then reported by the assertion
// phase as a tool that produced no observation. Failing here instead would turn
// "one fixture drifted" into a stack trace at the first tool, hiding every later
// one; the whole walk's coverage is the measurement, so the report has to be of
// the whole walk.
func (w *liveKeyWalk) driveResult(t *testing.T, tool string, args map[string]any) (string, map[string]any) {
	t.Helper()
	text, isErr := w.s.callAllowingError(t, tool, args)
	// aihub#593 (2026-09-11): a refusal whose code is the typed retryable
	// serialization 409 is not fixture drift — it is the server keeping its own
	// contract ("the transaction was rolled back ... retry the request") after
	// losing an SSI race to another DB-gated test binary on the same database,
	// the cross-package shape internal/domain's serialization_retry_test.go
	// header documents. Measured across 40 walk runs under that load: 5 died
	// this way, at four different legs — pf_claim_work_item (the state file
	// then carries no attempt credentials and adoptLiveGitWorktree fails),
	// pf_complete_attempt and pf_wrap (K10 then reports REACH_GAP /
	// GIT_WALK_GAP for a tool the server refused once), and pf_ship (the
	// in-band `ok:false` shape e2eRetryableSerializationRefusal documents).
	// Retrying on the CODE, bounded like serializationRetryAttempts, is what
	// every production caller of these tools is told to do; recording the
	// refusal as final held this walk to a weaker standard. Nothing observable
	// is weakened: a 40001 means the transaction rolled back, so the retried
	// call is the same request against the same state.
	for attempt := 1; e2eRetryableSerializationRefusal(text, isErr) &&
		attempt < e2eSerializationRetries; attempt++ {
		t.Logf("%s: attempt %d lost an SSI race, retrying: %s", tool, attempt, liveKeysAbbrev(text))
		time.Sleep(time.Duration(attempt) * 2 * time.Millisecond)
		text, isErr = w.s.callAllowingError(t, tool, args)
	}
	if isErr {
		w.failed[tool] = append(w.failed[tool], liveKeysAbbrev(text))
		return text, nil
	}
	var decoded map[string]any
	if err := json.Unmarshal([]byte(text), &decoded); err != nil {
		// Prose (slim-render) results carry no top-level keys. The corpus records
		// say the same of their own empty lists: "not measurable this way", not
		// "returns nothing".
		w.prose[tool] = true
		w.failed[tool] = append(w.failed[tool], "prose result: "+liveKeysAbbrev(text))
		return text, nil
	}
	set := w.observed[tool]
	if set == nil {
		set = map[string]bool{}
		w.observed[tool] = set
	}
	for k := range decoded {
		set[k] = true
	}
	return text, decoded
}

func (w *liveKeyWalk) keys(tool string) []string {
	out := make([]string, 0, len(w.observed[tool]))
	for k := range w.observed[tool] {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func liveKeysAbbrev(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	if len(s) > 160 {
		return s[:160] + "…"
	}
	return s
}

// ─────────────────────────── the golden file ─────────────────────────────────

// liveKeysFile is docs/mcp-cards/live-response-keys.json.
type liveKeysFile struct {
	WhatThisIs string                       `json:"what_this_is"`
	HowToRegen string                       `json:"how_to_regenerate"`
	Keys       map[string]map[string]string `json:"keys"`
}

// liveKeysRegenPlaceholder is what the regen writes for a key it has no reason
// for. The gate rejects it, so a regenerated file cannot be committed without
// somebody writing down why the key is there.
const liveKeysRegenPlaceholder = "WHY IS THIS KEY NOT IN THE aihub#412 CORPUS? — replace this line"

func readLiveKeysFile(t *testing.T) liveKeysFile {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(cardsRepoRoot, liveKeysFileRel))
	if err != nil {
		t.Fatalf("read %s: %v — this file is one of the two halves of the declaration K10 "+
			"checks, so a missing one is a failure, not an empty pass", liveKeysFileRel, err)
	}
	var f liveKeysFile
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("decode %s: %v", liveKeysFileRel, err)
	}
	if f.Keys == nil {
		f.Keys = map[string]map[string]string{}
	}
	return f
}

func writeLiveKeysFile(t *testing.T, f liveKeysFile) {
	t.Helper()
	raw, err := json.MarshalIndent(f, "", "  ")
	if err != nil {
		t.Fatalf("encode %s: %v", liveKeysFileRel, err)
	}
	path := filepath.Join(cardsRepoRoot, liveKeysFileRel)
	if err := os.WriteFile(path, append(raw, '\n'), 0o644); err != nil {
		t.Fatalf("write %s: %v", liveKeysFileRel, err)
	}
	t.Logf("PF_LIVE_KEYS_REGEN: rewrote %s", liveKeysFileRel)
}

// ─────────────────────────────────── K10 ─────────────────────────────────────

func TestE2ELiveResponseKeysAreDeclaredOnTheCards(t *testing.T) {
	s := newE2EStack(t)
	w := newLiveKeyWalk(s)
	runLiveKeyWalk(t, w)
	// aihub#501: the six git-dependent tools, folded into the SAME walk. The
	// golden file is checked by equality against (live \ card) across every tool,
	// so a second walk with a second assertion phase would need a second golden
	// file and the equality would stop meaning anything in either.
	runLiveGitKeyWalk(t, w)

	cards := readCards(t)
	golden := readLiveKeysFile(t)
	regen := os.Getenv("PF_LIVE_KEYS_REGEN") == "1"
	fresh := map[string]map[string]string{}

	driven := make([]string, 0, len(w.observed))
	for tool := range w.observed {
		driven = append(driven, tool)
	}
	sort.Strings(driven)

	checks, undeclared := 0, 0
	for _, tool := range driven {
		c, ok := cards[tool]
		if !ok {
			// K1/K2 in contract_cards_gate_test.go own coverage; a published tool
			// with no card is their failure, not this one's.
			continue
		}
		declared := map[string]bool{}
		for _, k := range c.block.ResponseKeysObserved {
			declared[k] = true
		}
		for _, k := range w.keys(tool) {
			if declared[k] {
				checks++
				continue
			}
			undeclared++
			reason := golden.Keys[tool][k]
			if regen {
				if fresh[tool] == nil {
					fresh[tool] = map[string]string{}
				}
				if reason == "" {
					reason = liveKeysRegenPlaceholder
				}
				fresh[tool][k] = reason
				continue
			}
			switch reason {
			case "":
				t.Errorf("K10 LIVE_UNDECLARED: the live %s response carries top-level key %q, and "+
					"neither %s nor %s declares it. A key a caller is handed that no card names is "+
					"the hop-5 contract drifting from the server in silence — the exact shape K7 "+
					"cannot see, because both of ITS sides are files. Fix it by adding the key to "+
					"%s with the reason it is not in aihub#412's corpus (the corpus is generated, "+
					"so the card cannot carry it until the corpus is re-extracted).",
					tool, k, c.path, liveKeysFileRel, liveKeysFileRel)
			case liveKeysRegenPlaceholder:
				t.Errorf("K10 LIVE_REASON_MISSING: %s declares %s.%s with the placeholder the regen "+
					"writes. The reason is the whole value of the entry: without it the file is a "+
					"list of keys somebody once saw, and nobody can tell a deliberate addition from "+
					"a projection that started leaking.", liveKeysFileRel, tool, k)
			default:
				checks++
			}
		}
	}

	// ── the golden file may not hold anything the walk did not just see ──────
	//
	// Equality, not containment. See the header: a permission list only grows,
	// and then the ceiling below stops bounding anything real.
	if !regen {
		for _, tool := range sortedLiveKeyTools(golden.Keys) {
			for _, k := range sortedLiveKeys(golden.Keys[tool]) {
				if w.observed[tool] == nil {
					t.Errorf("K10 LIVE_STALE_TOOL: %s declares %s.%s but the walk observed no JSON "+
						"result from %s at all. Either the entry outlived the tool or the walk "+
						"stopped driving it; both make this file a record of something that is no "+
						"longer measured.", liveKeysFileRel, tool, k, tool)
					continue
				}
				if !w.observed[tool][k] {
					t.Errorf("K10 LIVE_STALE_KEY: %s declares %s.%s but the live response does not "+
						"carry that key. Delete the entry — an exemption for a key nothing emits is "+
						"debt that reads like coverage.", liveKeysFileRel, tool, k)
					continue
				}
				c, ok := cards[tool]
				if !ok {
					continue
				}
				for _, cardKey := range c.block.ResponseKeysObserved {
					if cardKey == k {
						t.Errorf("K10 LIVE_REDUNDANT: %s declares %s.%s, but %s now names it too. "+
							"The card is where a reader looks, so the entry is spent — delete it "+
							"and take the ceiling down with it.", liveKeysFileRel, tool, k, c.path)
					}
				}
			}
		}
	}

	// ── the walk itself has to have measured something ──────────────────────
	if len(driven) < floorLiveTools {
		t.Errorf("K10 FLOOR_LIVE_TOOLS: only %d tool(s) returned a JSON object, floor is %d. Every "+
			"arm above is per-tool, so a walk whose fixtures rotted until nothing succeeded would "+
			"report green — the shape of pass this floor refuses. Refusals this run: %v",
			len(driven), floorLiveTools, w.failed)
	}
	if checks < floorLiveKeyChecks {
		t.Errorf("K10 FLOOR_LIVE_KEYS: only %d (tool, key) pair(s) were confirmed declared, floor "+
			"is %d. FLOOR_LIVE_TOOLS above is satisfied by tools that each answer `{}`; this is the "+
			"arm that says the responses had content in them.", checks, floorLiveKeyChecks)
	}
	if !regen && undeclared > maxUndeclaredLiveKeys {
		t.Errorf("K10 CEILING_UNDECLARED: %d live key(s) are declared only in %s, ceiling is %d. "+
			"Each is a key callers receive that the tool's card does not name. Raising the ceiling "+
			"is a decision somebody signs; lowering it is free once the corpus is re-extracted and "+
			"the cards absorb the keys.", undeclared, liveKeysFileRel, maxUndeclaredLiveKeys)
	}

	// ── every published tool is accounted for, one of three ways ────────────
	//
	// Observed (its keys were compared above), prose (it was driven and has no
	// keys), or declared out of reach. Silence is the one answer this arm does
	// not accept, because a tool that quietly stops being driven is a tool whose
	// card quietly stops being checked.
	for _, tool := range sortedCardNames(cards) {
		_, outOfReach := liveWalkOutOfReach[tool]
		_, proseOnly := liveWalkProseOnly[tool]
		switch {
		case w.observed[tool] != nil:
			if outOfReach {
				t.Errorf("K10 REACH_STALE: %s is listed in liveWalkOutOfReach but the walk drove it. "+
					"Delete the entry; a reason for not measuring something that IS measured is how "+
					"a walk shrinks back without anyone noticing.", tool)
			}
			if proseOnly {
				t.Errorf("K10 PROSE_STALE: %s is listed in liveWalkProseOnly but the walk observed a "+
					"JSON object from it, so it does have a key surface and that surface is now "+
					"being checked. Delete the entry — a tool listed as keyless while returning "+
					"keys reads as coverage of something nothing measures.", tool)
			}
		case w.prose[tool]:
			if outOfReach {
				t.Errorf("K10 REACH_STALE: %s is listed in liveWalkOutOfReach but the walk drove it "+
					"(the result was prose, not a refusal). Move the entry to liveWalkProseOnly.", tool)
			}
			if !proseOnly {
				t.Errorf("K10 PROSE_UNDECLARED: the walk drove %s and its result was not a JSON "+
					"object, so no key of it was compared against its card. That is legitimate for a "+
					"tool that renders prose and a silent hole for one that does not — declare which "+
					"in liveWalkProseOnly. Result: %v", tool, w.failed[tool])
			} else if keys := cards[tool].block.ResponseKeysObserved; len(keys) > 0 {
				t.Errorf("K10 PROSE_CARD_CLAIMS_KEYS: %s is declared prose-only, and its live result "+
					"really carries no top-level keys, but its card names %d of them (%v). One of the "+
					"two is wrong, and the card is what a reader believes.", tool, len(keys), keys)
			}
		default:
			if !outOfReach {
				t.Errorf("K10 REACH_GAP: %s is published and carries a card, but the walk produced no "+
					"live observation of it (refusals: %v). Either drive it or add it to "+
					"liveWalkOutOfReach with the reason it cannot be driven.", tool, w.failed[tool])
			}
		}
	}

	// A prose-only entry for a tool the walk never drove at all is the fourth
	// direction, and it is checked here rather than left to REACH_GAP above:
	// that arm would report "nothing drove this tool" and say nothing about the
	// declaration claiming it was driven and keyless.
	for _, tool := range sortedLiveKeys(liveWalkProseOnly) {
		if !w.prose[tool] && w.observed[tool] == nil {
			t.Errorf("K10 PROSE_NOT_DRIVEN: liveWalkProseOnly declares %s carries no keys, but the "+
				"walk never drove it (refusals: %v). The entry asserts a measurement that was not "+
				"taken, which is the shape of an exemption outliving the thing it exempted.",
				tool, w.failed[tool])
		}
	}

	// ── the aihub#501 arm drove all six of the git-dependent tools ──────────
	assertLiveGitWalkDroveAllSix(t, w)

	if regen {
		golden.Keys = fresh
		writeLiveKeysFile(t, golden)
	}
	t.Logf("K10: %d tools driven live, %d (tool, key) pairs confirmed declared, %d of them via %s",
		len(driven), checks, undeclared, liveKeysFileRel)
	// Every non-JSON result, logged unconditionally rather than only inside the
	// floor failures. The counts above move for two unrelated reasons — a tool
	// stopped being driven, or a response changed shape — and without this line
	// the two are indistinguishable in a CI log, which is how a flake in a walk
	// this long stays unexplained. pf_diff appears here on every green run: its
	// result is a diff, which is the whole content of liveWalkProseOnly.
	if len(w.failed) > 0 {
		t.Logf("K10: non-JSON results this run (expected: %d prose-only tool(s)): %v",
			len(liveWalkProseOnly), w.failed)
	}
}

func sortedLiveKeyTools(m map[string]map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sortedLiveKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sortedCardNames(cards map[string]*card) []string {
	out := make([]string, 0, len(cards))
	for k := range cards {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// ────────────────────────────── the script ───────────────────────────────────

// runLiveKeyWalk drives every reachable tool once, in an order that satisfies
// each one's preconditions. The fixtures are deliberately ordinary: what is
// measured is the keys a normal successful call carries, not the edge cases.
func runLiveKeyWalk(t *testing.T, w *liveKeyWalk) {
	t.Helper()
	s := w.s
	ctx := context.Background()
	t.Setenv("POLYFORGE_WORKSPACE_ROOT", t.TempDir())
	stamp := time.Now().UnixNano()

	// ── identity and projects ───────────────────────────────────────────────
	w.drive(t, "pf_whoami", map[string]any{})
	w.drive(t, "pf_list_projects", map[string]any{})

	project := fmt.Sprintf("p_livekeys_%d", stamp)
	w.drive(t, "pf_create_project", map[string]any{
		"name": project, "description": "aihub#482 live response-key walk",
	})
	w.drive(t, "pf_update_project", map[string]any{
		"name": project, "description": "aihub#482 live response-key walk, updated",
	})
	w.drive(t, "pf_rotate_identifier", map[string]any{"name": project})

	// ── users and keys ──────────────────────────────────────────────────────
	user := w.drive(t, "pf_create_user", map[string]any{
		"display_name": fmt.Sprintf("live key walk %d", stamp),
		"user_type":    "machine",
	})
	userID, _ := user["id"].(string)
	w.drive(t, "pf_list_users", map[string]any{})
	if userID != "" {
		w.drive(t, "pf_update_user", map[string]any{
			"id": userID, "display_name": fmt.Sprintf("live key walk %d, renamed", stamp),
		})
		key := w.drive(t, "pf_create_api_key", map[string]any{"user_id": userID, "name": "live key walk"})
		if keyID, _ := key["key_id"].(string); keyID != "" {
			w.drive(t, "pf_revoke_api_key", map[string]any{"user_id": userID, "key_id": keyID})
		}
	}

	// ── work items ──────────────────────────────────────────────────────────
	//
	// The goals below are deliberately unlike one another: CreateWorkItem runs
	// goal-similarity dedup against live rows and answers 409 CONFLICT_CANDIDATES
	// on a near-miss, which would cost this walk a tool.
	subject := w.drive(t, "pf_create_work_item", map[string]any{
		"project": s.project,
		"goal":    fmt.Sprintf("carry one work item through the whole attempt lifecycle %d", stamp),
		"wi_type": "fix_bug",
	})
	wiID, _ := subject["id"].(string)
	w.drive(t, "pf_get_work_item", map[string]any{"work_item_id": wiID})
	w.drive(t, "pf_update_work_item", map[string]any{"work_item_id": wiID, "priority": "high"})
	w.drive(t, "pf_list_work_items", map[string]any{"project": s.project})
	// aihub#360: the same tool again WITH a query — the `lexical` section is
	// present exactly when query= is sent, so without this drive the key would
	// be live on real callers and invisible to this walk. The walk unions keys
	// across drives of one tool, so this widens the observed surface rather
	// than replacing it.
	w.drive(t, "pf_list_work_items", map[string]any{"project": s.project, "query": "attempt lifecycle"})
	w.drive(t, "pf_batch_create_work_items", map[string]any{
		"project": s.project,
		"items": []any{
			map[string]any{"goal": fmt.Sprintf("teach the renderer about nested tables %d", stamp), "wi_type": "chore"},
			map[string]any{"goal": fmt.Sprintf("retire the unused vendored yaml parser %d", stamp), "wi_type": "chore"},
		},
	})

	blocker := w.drive(t, "pf_create_work_item", map[string]any{
		"project": s.project,
		"goal":    fmt.Sprintf("be the blocking side of one dependency edge %d", stamp),
		"wi_type": "chore",
	})
	blockerID, _ := blocker["id"].(string)
	w.drive(t, "pf_create_dependency", map[string]any{
		"blocking_wi_id": blockerID, "blocked_wi_id": wiID, "kind": "blocks",
	})
	w.drive(t, "pf_list_dependencies", map[string]any{"work_item_id": wiID})
	w.drive(t, "pf_remove_dependency", map[string]any{
		"blocking_wi_id": blockerID, "blocked_wi_id": wiID, "kind": "blocks",
	})
	w.drive(t, "pf_get_ready_queue", map[string]any{"project": s.project})

	// ── the attempt ─────────────────────────────────────────────────────────
	//
	// No session_info: it is not a published parameter of this tool, and passing
	// it makes the server answer with a `request_adjusted.unknown_params` entry
	// (aihub#389) — a key that would then be recorded as part of the tool's live
	// surface when it is really an artifact of calling it wrong. The tool mints
	// the secret and writes the state file itself, which is what a real caller
	// relies on anyway.
	w.drive(t, "pf_claim_work_item", map[string]any{
		"work_item_id": wiID, "idempotency_key": fmt.Sprintf("livekeys-%d", stamp),
	})
	w.drive(t, "pf_acquire_locks", map[string]any{"work_item_id": wiID})
	w.drive(t, "pf_predict_conflicts", map[string]any{
		"declared_resources": []any{
			map[string]any{"type": "path", "uri": "file:internal/mcp/card_response_keys_live_e2e_db_test.go"},
		},
	})

	step := w.drive(t, "pf_get_step", map[string]any{"work_item_id": wiID})
	stepID, _ := step["current_step"].(string)
	if stepID == "" {
		stepID = "spec"
	}
	stepAttempt := fmt.Sprintf("sa_livekeys_%d", stamp)
	w.drive(t, "pf_update_step", map[string]any{
		"work_item_id": wiID, "step_id": stepID, "status": "in_progress",
		"step_attempt_id": stepAttempt,
	})

	// ── memory, including the artifact the spec step cannot complete without ─
	remembered := w.drive(t, "pf_remember", map[string]any{
		"project":    s.project,
		"type":       "experience.debug",
		"content":    fmt.Sprintf("a memory the live response-key walk reads back %d", stamp),
		"visibility": "project",
		"dedup_mode": "off",
	})
	memID, _ := remembered["id"].(string)
	w.drive(t, "pf_get_memory", map[string]any{"memory_id": memID})
	w.drive(t, "pf_update_memory", map[string]any{
		"memory_id": memID, "work_item_id": wiID,
		"content": fmt.Sprintf("a memory the live response-key walk reads back %d, revised", stamp),
	})
	w.drive(t, "pf_activate_memory", map[string]any{"memory_id": memID})
	w.drive(t, "pf_reinforce_memory", map[string]any{
		"memory_id": memID, "work_item_id": wiID,
		"additional_context": "reinforced by the aihub#482 live response-key walk",
	})
	w.drive(t, "pf_recall", map[string]any{"project": s.project, "query": "live response-key walk"})

	artifact := w.drive(t, "pf_save_artifact", map[string]any{
		"work_item_id": wiID, "type": "methodology.spec",
		"content": "# aihub#482\n\nthe spec artifact the spec step requires before it can complete",
	})
	artifactID, _ := artifact["id"].(string)
	if artifactID != "" {
		// pf_adopt_artifact / pf_close_artifact / pf_ignore_artifact were driven
		// here until aihub#446 retired them (aihub#411 T2-7). Their three entries
		// in live-response-keys.json went with them: the equality arm above refuses
		// a golden entry for a tool the walk no longer observes, so the file and
		// this block cannot drift apart in that direction.

		// pf_resolve_commit answers a review annotation, and annotations are made
		// through the /ui viewer, which no MCP tool reaches. The row is seeded
		// directly so the tool can be driven at all; everything downstream of the
		// seed — the lookup, the permission check, the response — is the real one.
		commitID := fmt.Sprintf("cmt_livekeys_%d", stamp)
		entry, err := json.Marshal([]map[string]any{{
			"id":             commitID,
			"author_user_id": "u_echo_e2e",
			"author_display": "u_echo_e2e",
			"body":           "does this paragraph still hold?",
			"status":         "open",
			"created_at":     time.Now().UTC().Format(time.RFC3339),
		}})
		if err != nil {
			t.Fatalf("marshal seeded commit: %v", err)
		}
		if _, err := s.pool.Exec(ctx,
			`UPDATE memories SET commits=$2 WHERE id=$1`, artifactID, entry); err != nil {
			t.Fatalf("seed artifact commit: %v", err)
		}
		w.drive(t, "pf_resolve_commit", map[string]any{
			"memory_id": artifactID, "commit_id": commitID, "reply": "it does; leaving as written",
		})
	}
	w.drive(t, "pf_redact_memory", map[string]any{
		"memory_id": memID, "reason": "the live response-key walk cleans up after itself",
	})

	// The spec step can complete now that a methodology.spec artifact exists.
	w.drive(t, "pf_update_step", map[string]any{
		"work_item_id": wiID, "step_id": stepID, "status": "completed",
		"step_attempt_id": stepAttempt, "next_step": "plan",
	})
	w.drive(t, "pf_emit_event", map[string]any{
		"work_item_id": wiID, "event_type": "note",
		"payload": map[string]any{"text": "the live response-key walk was here"},
	})
	w.drive(t, "pf_read_events", map[string]any{"work_item_id": wiID})
	w.drive(t, "pf_complete_attempt", map[string]any{
		"work_item_id": wiID, "status": "wrapped",
		"note": "the live response-key walk finished with this work item",
		// aihub#350: a wrap that omits derived is refused before any request.
		"derived": []any{},
		// The walk left `plan` in progress; without this the server answers 409
		// CONFLICT_STEP_IN_PROGRESS and the tool goes unmeasured.
		"force_terminate_step": true,
	})

	// ── one subject per terminal transition ─────────────────────────────────
	//
	// pause, takeover and cancel each END an attempt, so they cannot share one.
	for _, tc := range []struct{ goal, tool string }{
		{"hold an attempt open long enough to be paused", "pf_pause_attempt"},
		{"have its attempt stolen by a takeover", "pf_force_takeover"},
	} {
		wi := w.drive(t, "pf_create_work_item", map[string]any{
			"project": s.project,
			"goal":    fmt.Sprintf("%s %d", tc.goal, stamp),
			"wi_type": "chore",
		})
		id, _ := wi["id"].(string)
		if id == "" {
			continue
		}
		w.drive(t, "pf_claim_work_item", map[string]any{
			"work_item_id": id, "idempotency_key": fmt.Sprintf("livekeys-%s-%d", tc.tool, stamp),
		})
		args := map[string]any{"work_item_id": id}
		if tc.tool == "pf_force_takeover" {
			args["reason"] = "the live response-key walk needs a takeover response to read"
		}
		w.drive(t, tc.tool, args)
	}
	w.drive(t, "pf_cancel_work_item", map[string]any{
		"work_item_id": blockerID, "reason": "the live response-key walk is done with it",
	})
}
