package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/GMISWE/ieops-aihub/internal/config"
	"github.com/GMISWE/ieops-aihub/pkg/client"
	"gopkg.in/yaml.v3"
	"strings"
)

// RunInit fetches the scenario phase config from aihub and writes it to
// <wsRoot>/.polyforge/phase.yaml.
//
// With --apply: also applies the local .polyforge/phase.yaml back to aihub
// via a PATCH (CAS update, using the embedded __version__ field).
func RunInit(ctx context.Context, c *client.Client, cfg *config.Config, wsRoot string, args []string) {
	// Ensure ~/.polyforge/config.toml exists with a stable machine_id (§9.5.3).
	mc, err := config.EnsureMachineConfig()
	if err != nil {
		fmt.Fprintf(os.Stderr, "pf init: config.toml: %v\n", err)
	} else if mc.Auth.APIKey == "" && mc.Auth.APIKeyEnv == "" {
		fmt.Fprintf(os.Stderr, "pf init: ~/.polyforge/config.toml created (machine_id=%s)\n", mc.MachineID)
		fmt.Fprintf(os.Stderr, "         Add your API key:\n")
		fmt.Fprintf(os.Stderr, "           [auth]\n")
		fmt.Fprintf(os.Stderr, "           api_key = \"your-key-here\"\n")
	}

	apply := len(args) > 0 && args[0] == "--apply"

	// Determine scenario from config (or default to "coding").
	scenario := "coding"
	if cfg != nil && cfg.Scenario != "" {
		scenario = cfg.Scenario
	}

	phaseDir := filepath.Join(wsRoot, ".polyforge")
	phaseFile := filepath.Join(phaseDir, "phase.yaml")

	if apply {
		runInitApply(ctx, c, scenario, phaseFile)
		return
	}

	// GET /v1/scenario_configs/:scenario
	result, err := c.GetScenarioConfig(ctx, scenario)
	if err != nil {
		fmt.Fprintf(os.Stderr, "pf init: failed to fetch scenario config: %v\n", err)
		os.Exit(1)
	}

	// Write to .polyforge/phase.yaml in the workspace root.
	if err := os.MkdirAll(phaseDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "pf init: mkdir .polyforge: %v\n", err)
		os.Exit(1)
	}

	// Embed version for CAS on future --apply.
	if v, ok := result["version"]; ok {
		result["__version__"] = v
	}

	b, err := yaml.Marshal(result)
	if err != nil {
		fmt.Fprintf(os.Stderr, "pf init: marshal phase.yaml: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(phaseFile, b, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "pf init: write phase.yaml: %v\n", err)
		os.Exit(1)
	}

	ver := result["version"]
	fmt.Printf("ok .polyforge/phase.yaml written (scenario: %s, version: %v)\n", scenario, ver)

	// Write .polyforge/usage.md — polyforge v1 workspace guide.
	usageFile := filepath.Join(phaseDir, "usage.md")
	if err := writeUsageMd(usageFile); err != nil {
		fmt.Fprintf(os.Stderr, "pf init: write usage.md: %v\n", err)
	} else {
		fmt.Printf("ok .polyforge/usage.md written\n")
	}

	// Ensure CLAUDE.md references @.polyforge/usage.md (not @.claude/polyforge.md).
	claudeMd := filepath.Join(wsRoot, "CLAUDE.md")
	if err := ensureClaudeMdRef(claudeMd); err != nil {
		fmt.Fprintf(os.Stderr, "pf init: update CLAUDE.md: %v\n", err)
	}
}

// writeUsageMd creates <wsRoot>/.polyforge/usage.md with the polyforge v1 workspace guide.
// This replaces the old .claude/polyforge.md pattern from polyforge-v3.
func writeUsageMd(path string) error {
	const content = `# polyforge v1 workspace guide

> **State authority = aihub PostgreSQL** at the URL in ~/.polyforge/config.toml.
> Per-wi task worktrees materialize at pf3.<shortid>/<repo>/ on /pf-work.

## Iron Rules

**IR1 — Work-item-gated writes**
Every git commit/push/PR and Edit/Write under .repo/ must happen inside a
claimed wi worktree (pf3.<shortid>/<repo>/). No env-var bypass.

**IR2 — Analyze obstacles; track blockers as wi's**
When you hit an obstacle, find the root cause. If it's a bug or out of
scope, create a wi to track it — don't route around it.

**IR3 — MCP unavailable → stop**
If the polyforge MCP can't reach aihub, stop and report. Do not fall back
to direct HTTP calls. Use /reload-plugins or restart to reconnect.

**IR4 — One feature = one spec + one plan**
Every non-trivial wi requires a spec artifact and a plan before coding.

---

## Daily workflow

` + "```" + `bash
# Start work
/pf-work --goal "..."           # create + claim wi
/pf-work <wi_id>                # claim existing wi

# Check status
/pf-status                      # LCRS six-segment ready queue

# Layer 2 methodology (inside a claimed wi)
/pf-spec  /pf-plan  /pf-execute  /pf-retro

# Stop work
/pf-stop --pause                # release, keep state
/pf-stop --wrap                 # terminal success
/pf-stop --fail                 # terminal failure

# Misc
/pf-status <wi_id>              # single wi detail + timeline
` + "```" + `

---

## ~/.polyforge/config.toml (machine-level)

` + "```" + `toml
machine_id = "<auto-generated UUID>"
[auth]
api_key = "your-key-here"
[server]
url = "http://your-aihub-host"
` + "```" + `

---

> Generated by polyforge init. Edit this file to add workspace-specific notes.
> Iron Rules take precedence over everything in this file.
`
	if _, err := os.Stat(path); err == nil {
		return nil // already exists — don't overwrite user edits
	}
	return os.WriteFile(path, []byte(content), 0644)
}

// ensureClaudeMdRef ensures CLAUDE.md references @.polyforge/usage.md.
// If CLAUDE.md already references @.claude/polyforge.md, replaces it.
// If CLAUDE.md doesn't exist yet, creates a minimal one.
func ensureClaudeMdRef(claudeMd string) error {
	const newRef = "@.polyforge/usage.md"
	const oldRef = "@.claude/polyforge.md"

	b, err := os.ReadFile(claudeMd)
	if os.IsNotExist(err) {
		// Create a minimal CLAUDE.md
		content := newRef + "\n"
		if writeErr := os.WriteFile(claudeMd, []byte(content), 0644); writeErr != nil {
			return writeErr
		}
		fmt.Printf("ok CLAUDE.md created with %s\n", newRef)
		return nil
	}
	if err != nil {
		return err
	}

	s := string(b)
	if strings.Contains(s, newRef) {
		return nil // already correct
	}
	if strings.Contains(s, oldRef) {
		s = strings.ReplaceAll(s, oldRef, newRef)
		if writeErr := os.WriteFile(claudeMd, []byte(s), 0644); writeErr != nil {
			return writeErr
		}
		fmt.Printf("ok CLAUDE.md updated: %s → %s\n", oldRef, newRef)
	}
	return nil
}

// runInitApply reads the local phase.yaml and PATCHes it back to aihub (CAS).
func runInitApply(ctx context.Context, c *client.Client, scenario, phaseFile string) {
	b, err := os.ReadFile(phaseFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "pf init --apply: read phase.yaml: %v\n", err)
		os.Exit(1)
	}

	var content map[string]any
	if err := yaml.Unmarshal(b, &content); err != nil {
		fmt.Fprintf(os.Stderr, "pf init --apply: parse phase.yaml: %v\n", err)
		os.Exit(1)
	}

	// Extract embedded __version__ for CAS.
	// Server schema (UpdateScenarioConfigRequest) reads the field as "version" (§4.3 PUT body).
	expectedVersion := content["__version__"]
	delete(content, "__version__")

	// Normalize version to int for the server's CAS check (handles yaml numeric decoding).
	var versionInt int
	switch v := expectedVersion.(type) {
	case int:
		versionInt = v
	case int64:
		versionInt = int(v)
	case float64:
		versionInt = int(v)
	}

	body := map[string]any{
		"content": content,
		"version": versionInt,
	}

	result, err := c.UpdateScenarioConfig(ctx, scenario, body)
	if err != nil {
		fmt.Fprintf(os.Stderr, "pf init --apply: PATCH scenario config: %v\n", err)
		os.Exit(1)
	}

	newVer := result["version"]
	fmt.Printf("ok phase.yaml applied to aihub (scenario: %s, version: %v)\n", scenario, newVer)

	// Update the local file with the new version.
	content["__version__"] = newVer
	updated, _ := yaml.Marshal(content)
	_ = os.WriteFile(phaseFile, updated, 0644)
}

