// Command polyforge runs the polyforge v1 MCP server (stdio JSON-RPC 2.0)
// or executes a CLI subcommand when arguments are provided.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"sort"
	"sync"
	"syscall"
	"time"

	"github.com/GMISWE/ieops-aihub/internal/cli"
	"github.com/GMISWE/ieops-aihub/internal/config"
	"github.com/GMISWE/ieops-aihub/internal/mcp"
	"github.com/GMISWE/ieops-aihub/internal/roles"
	"github.com/GMISWE/ieops-aihub/internal/version"
	"github.com/GMISWE/ieops-aihub/pkg/client"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	// CLI mode: any argument other than "serve" triggers CLI dispatch.
	if len(os.Args) > 1 && os.Args[1] != "serve" {
		runCLI(ctx, os.Args[1:])
		return
	}

	// MCP server mode (no args, or explicit "serve").
	fmt.Fprintf(os.Stderr, "polyforge MCP server %s (%s)\n", version.Version, version.GitCommit)

	// Load ~/.polyforge/config.toml (machine-level, §9.5.3).
	// EnsureMachineConfig also generates a stable machine_id on first run.
	mc, err := config.EnsureMachineConfig()
	if err != nil {
		fmt.Fprintf(os.Stderr, "config.toml: %v\n", err)
		os.Exit(1)
	}

	// codex agent-profile generation (aihub#642 plan step 10; corrected by
	// aihub#655): the ORIGINAL call here wrote step-<role>.toml files (with
	// `name`/`description`/`instructions` keys) into
	// plugins/polyforge/.codex-plugin/agents/, reporting success on every
	// boot with no proof codex could ever load the result. It could not:
	// aihub#655's investigation found codex has NO directory-scanning
	// subagent-discovery mechanism in this codex-cli version at all (the
	// removed DefaultCodexAgentsDir doc comment claiming one existed was
	// itself unverified), and separately, `name`/`description` are rejected
	// as unknown ConfigToml fields by --strict-config while `instructions`
	// is worse: silently ACCEPTED with no error and then never delivered to
	// the model's prompt (confirmed via `codex debug prompt-input` marker
	// testing) -- a parser that takes a field and drops it is exactly the
	// silently-unloadable failure mode this wi exists to close.
	// `developer_instructions` is the field confirmed to actually reach the
	// model. All live-verified against codex-cli 0.154.0 via `codex exec
	// --strict-config -p <name> ...` against a real profile file, scratch
	// $CODEX_HOME, several rounds (see internal/roles/render_codex.go's
	// RenderCodexProfiles doc comment).
	//
	// The fix: write a codex CONFIG PROFILE file per role directly under
	// $CODEX_HOME (default ~/.codex), named step-<role>.config.toml -- the
	// literal filename codex's own `-p <name>` / `--profile <name>` flag
	// requires -- containing only `model`/`sandbox_mode`/`developer_instructions`.
	// This shape is live-verified loadable: `codex exec --strict-config -p
	// step-<role> ...` against output generated by this exact code path
	// parses with zero config errors before falling through to normal
	// execution.
	//
	// Timing (the same wi also had to decide this, entangled with the two
	// field/directory defects per aihub#642's "ships, reports success,
	// unloadable" failure mode -- moving timing without re-proving
	// loadability would repeat exactly that): investigated moving generation
	// to codex's SessionStart hook instead of this boot path. Built a real
	// local codex plugin marketplace declaring a SessionStart hook, installed
	// it (`codex plugin list` confirmed "installed, enabled"), then ran
	// `codex exec --dangerously-bypass-hook-trust --json ...` under the same
	// scratch $CODEX_HOME. The hook's marker file never appeared, and the
	// --json event stream (which does carry structured lifecycle/error
	// items) shows no hook-related event anywhere in the run, including
	// immediately after `thread.started` -- before any network call, so the
	// run's later 401s (this scratch environment had no credentials) cannot
	// explain away a hook that should fire at thread/session creation, if it
	// fires under headless `codex exec` at all. That is meaningful evidence
	// SessionStart hooks do not fire under headless `codex exec` -- the exact
	// invocation mode aihub#654's future headless orchestrator would use --
	// but not certain proof: this scratch environment never reached a fully
	// authenticated turn, so a design where hook dispatch is gated behind
	// that point cannot be ruled out from this test alone.
	//
	// Decision: KEEP boot-time regeneration, unmoved. It is the strictly
	// safer choice on the evidence available -- MCP server boot happens on
	// every invocation path, interactive or headless, where a SessionStart
	// hook is scoped to codex's interactive-session lifecycle and, per the
	// test above, may not fire for headless `exec` at all -- and every codex
	// session already boots this server fresh, so boot-time regen keeps the
	// same stay-in-sync property aihub#642's original rationale relied on.
	//
	// Gated on the codex CLI actually being installed (exec.LookPath): with
	// no codex binary nothing will ever read $CODEX_HOME, so this silently
	// no-ops on cc/pi-only machines instead of writing files nobody asked
	// for -- replacing DefaultCodexAgentsDir's old cwd-based
	// ".codex-plugin exists" gate, which made sense for a plugin-relative
	// output directory but not for a $HOME-relative one. Errors are a
	// warning only, NEVER fatal: role generation must not be able to break
	// MCP server startup for anyone.
	if _, err := exec.LookPath("codex"); err == nil {
		if err := generateCodexProfiles(mc); err != nil {
			fmt.Fprintf(os.Stderr, "polyforge: codex profile generation failed (non-fatal, server continues): %v\n", err)
		}
	}

	// Load .polyforge.yaml from POLYFORGE_WORKSPACE_ROOT, or by walking up from
	// cwd to find .polyforge.yaml (non-fatal). When config.toml has api_key +
	// server.url the workspace config is optional, allowing the MCP server to
	// run from any directory (global plugin install).
	wsRoot := os.Getenv("POLYFORGE_WORKSPACE_ROOT")
	if wsRoot == "" {
		wsRoot = config.FindWorkspaceRoot()
	}
	cfg, _ := config.Load(wsRoot) // non-fatal: config.toml takes priority

	// Resolve API key: POLYFORGE_API_KEY > config.toml [auth] > .polyforge.yaml api_key_env.
	apiKey := mc.ResolveAPIKey()
	if apiKey == "" && cfg != nil {
		apiKey = os.Getenv(cfg.AIHub.APIKeyEnv)
	}
	if apiKey == "" {
		fmt.Fprintf(os.Stderr, "API key not set: configure ~/.polyforge/config.toml [auth] api_key\n")
		os.Exit(1)
	}

	// Resolve aihub URL: POLYFORGE_AIHUB_URL > config.toml [server] >
	// .polyforge.yaml > the endpoint compiled into this binary (aihub#335).
	aihubURL, _ := config.EffectiveAihubURL(mc, workspaceAihubURL(cfg))

	aihubClient := client.New(aihubURL, apiKey)
	server := mcp.New(cfg, aihubClient)

	if err := server.Serve(ctx); err != nil {
		fmt.Fprintf(os.Stderr, "server error: %v\n", err)
		os.Exit(1)
	}
}

// codexProfileCatalogProbe is a minimal, main-package-local equivalent of
// internal/cli's unexported codexCatalogProbe: shells out to `codex debug
// models` and parses its real single-line JSON
// `{"models":[{"slug":"..."}]}` output. Duplicated rather than reused
// because internal/cli/roles_generate.go is not one of this wi's
// declared_resources; the alternative was passing probe=nil to
// cli.ResolveModel, which would silently drop aihub#642 AC6's live
// catalog validation for the one path this wi controls. Best-effort, at
// most once per process: if the codex CLI is missing, not authenticated, or
// the command fails for any reason, every model is conservatively treated
// as unavailable -- generation never guesses a model ID.
type codexProfileCatalogProbe struct {
	once   sync.Once
	models map[string]bool
	err    error
	// timeout overrides codexProbeTimeout, and exists so the test that proves
	// the deadline works does not have to spend the production one waiting for
	// it. Zero means the shipped default, so every non-test construction — all
	// of which use the zero value — gets codexProbeTimeout without naming it.
	//
	// A field rather than a package var: a var would be mutable global state
	// shared by whatever else lands in package main, and the thing being made
	// configurable here belongs to this probe.
	timeout time.Duration
}

// effectiveTimeout is codexProbeTimeout unless this probe was built with one.
func (p *codexProfileCatalogProbe) effectiveTimeout() time.Duration {
	if p.timeout > 0 {
		return p.timeout
	}
	return codexProbeTimeout
}

// codexProbeTimeout bounds the one subprocess this file runs before the MCP
// server begins serving.
//
// 🔴 HANGING IS NOT AN ERROR, and that is the whole defect this constant exists
// for. The call site treats a probe failure as a warning and carries on, which
// makes every FAILURE mode of `codex debug models` harmless — but a codex that
// neither succeeds nor fails (an auth prompt waiting on a tty it does not have,
// a network read with no deadline) returns from neither branch, and
// exec.Command has no deadline of its own. This runs in main() BEFORE
// server.Serve, so a hung codex does not degrade codex profile generation: it
// stops this process from ever speaking MCP. Every Claude Code / pi session on
// the machine starts its own polyforge MCP server, so one wedged codex binary
// presents as "MCP will not connect" everywhere at once — the IR3 symptom, with
// a cause nothing in the polyforge process is even logging, because the process
// is blocked before its first line of protocol.
//
// The value is a ceiling on a local process listing a static catalog, not a
// budget for it: `codex debug models` answers in milliseconds when it answers at
// all, so 5s is far past any honest slow path and still an imperceptible
// one-time cost on a boot that is already doing config and network setup. It is
// deliberately NOT tied to the server's own context: cancelling this probe must
// abandon the probe, never the server.
//
// ⚠️ A TIMEOUT IS THE FIX, NOT BACKGROUNDING IT. Moving the probe off the boot
// path would remove the stall and also remove the ordering generateCodexProfiles
// depends on — it writes $CODEX_HOME profiles that a codex session started right
// after this one is entitled to find. Bounding the wait keeps the ordering and
// costs a known, small amount.
const codexProbeTimeout = 5 * time.Second

// codexProbeWaitDelay is the grace period after cancellation, and WITHOUT IT THE
// TIMEOUT ABOVE DOES NOT ACTUALLY BOUND ANYTHING.
//
// 🔴 MEASURED WHILE WRITING THIS FIX, and it is the reason the fix is two
// constants rather than one. exec.CommandContext cancels by killing the process
// it started — and only that process. Output() does not return when the child
// dies; it returns when the stdout pipe reaches EOF, which happens when the LAST
// holder of the write end closes it. A child that forked before hanging leaves a
// grandchild holding that pipe, so Wait blocks on the pipe long after the child
// is dead and the deadline has passed.
//
// The first version of this fix had the context and no WaitDelay. Against a
// `/bin/sh` wrapper that exec'd `sleep 600` — the exact shape of a wrapper
// script, which is how codex is installed by several package managers — the
// probe did not return at all: the shell was killed on schedule, the sleep
// survived holding the pipe, and `go test` had to be killed by hand after two
// and a half minutes. A timeout that fires and then blocks anyway is worse than
// no timeout, because it reads as fixed.
//
// WaitDelay is the documented remedy for both halves (a child that ignores the
// kill, and a child that exits leaving its pipes open): Wait force-closes the
// descriptors and returns this long after cancellation. One second is generous
// for a local process already sent a signal, and it makes the worst case
// codexProbeTimeout + codexProbeWaitDelay = 6s, which is the number the boot
// path is actually bounded by.
//
// ⚠️ WHAT THIS DOES NOT DO, stated so nobody reads it as more than it is: the
// grandchild is not reaped, so a hung codex that forked stays hung, detached.
// That is strictly better than before — the same process was hung either way and
// used to take every MCP session on the machine down with it — but it is not a
// process-group kill, and if orphaned codex processes ever show up in anger the
// fix is SysProcAttr{Setpgid: true} plus a cmd.Cancel that signals -pgid, not a
// longer delay here.
const codexProbeWaitDelay = 1 * time.Second

func (p *codexProfileCatalogProbe) load() {
	p.once.Do(func() {
		timeout := p.effectiveTimeout()
		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()
		cmd := exec.CommandContext(ctx, "codex", "debug", "models")
		// See codexProbeWaitDelay: the context alone kills the child and then
		// blocks on a pipe a grandchild still holds. Both lines are the fix.
		cmd.WaitDelay = codexProbeWaitDelay
		out, err := cmd.Output()
		if err != nil {
			// The timeout is reported as itself. context.DeadlineExceeded reaches
			// the caller as "signal: killed" from Output() alone, which reads like
			// an operator killed codex rather than like polyforge gave up on it,
			// and that is the one distinction whoever is debugging a boot stall
			// needs.
			if ctx.Err() != nil {
				p.err = fmt.Errorf("codex debug models: gave up after %s (%w); "+
					"codex profile generation is skipped for this boot", timeout, ctx.Err())
				return
			}
			p.err = fmt.Errorf("codex debug models: %w", err)
			return
		}
		var catalog struct {
			Models []struct {
				Slug string `json:"slug"`
			} `json:"models"`
		}
		if jsonErr := json.Unmarshal(out, &catalog); jsonErr != nil {
			p.err = fmt.Errorf("parse codex debug models output as JSON: %w", jsonErr)
			return
		}
		models := make(map[string]bool, len(catalog.Models))
		for _, m := range catalog.Models {
			if m.Slug != "" {
				models[m.Slug] = true
			}
		}
		p.models = models
	})
}

func (p *codexProfileCatalogProbe) HasModel(model string) (bool, error) {
	p.load()
	if p.err != nil {
		return false, p.err
	}
	return p.models[model], nil
}

// generateCodexProfiles loads every role definition, resolves each role's
// model against a live codex model-catalog probe (mirroring
// internal/cli.GenerateRoles's codex path, aihub#642 AC6), renders codex
// config-profile TOML via roles.RenderCodexProfiles, and writes each one to
// $CODEX_HOME/step-<role>.config.toml ($CODEX_HOME env var, default
// ~/.codex -- codex's own default). Unlike the old DefaultCodexAgentsDir
// call this replaces, this is NOT gated on any plugin-tree cwd check:
// profile files are $HOME-relative, not project-relative, so the only
// gating this needs is "is the codex CLI installed at all" (done by the
// caller via exec.LookPath before calling this).
func generateCodexProfiles(mc *config.MachineConfig) error {
	codexHome := os.Getenv("CODEX_HOME")
	if codexHome == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("resolve $HOME for default $CODEX_HOME: %w", err)
		}
		codexHome = filepath.Join(home, ".codex")
	}

	roleList, err := roles.LoadRoles()
	if err != nil {
		return fmt.Errorf("load roles: %w", err)
	}

	// 🔴 Resolved through the ONE resolver, not read straight off
	// mc.Roles.Tiers as this line used to be (aihub#673). This is one of the
	// two production readers of the tier table; the other is
	// internal/cli.generateRoles. If this boot path ignored the machine's
	// [roles] preset while `polyforge roles generate` and `polyforge drain`
	// honoured it, the same machine would resolve different models depending on
	// which entry point ran -- the exact "同一台机器两个口径" hazard aihub#673
	// was filed to close.
	//
	// No override is passed: this is a boot path with no command line. It
	// honours the machine-level [roles] preset and nothing else.
	//
	// An error is returned rather than swallowed, and the caller logs it
	// without exiting -- the pre-existing contract that role generation must
	// never be able to break MCP server startup still holds. A misspelled
	// preset therefore degrades to "codex profiles not regenerated this boot,
	// loudly", not to "server will not start".
	tiers, tierSource, err := mc.ResolveTiers("")
	if err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "polyforge: codex profiles: tier table from %s\n", tierSource)

	probe := &codexProfileCatalogProbe{}
	resolved := make(map[string]string, len(roleList))
	for _, r := range roleList {
		model, ok := cli.ResolveModel(tiers[r.Tier], "codex", probe)
		if !ok {
			// Loud and non-suppressible by design (AC7 parity with
			// internal/cli.generateRoles): no flag gates this line.
			fmt.Fprintf(os.Stderr,
				"polyforge: WARNING: no resolvable codex model candidate for tier %q (role %q) -- "+
					"generated profile will have NO model field and will inherit codex's own default "+
					"model instead. Configure ~/.polyforge/config.toml [roles.tiers] to fix this.\n",
				r.Tier, r.Name)
			continue // resolved[r.Name] stays unset, read back as "".
		}
		resolved[r.Name] = model
	}

	rendered, err := roles.RenderCodexProfiles(roleList, resolved)
	if err != nil {
		return fmt.Errorf("render codex profiles: %w", err)
	}

	if err := os.MkdirAll(codexHome, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", codexHome, err)
	}
	names := make([]string, 0, len(rendered))
	for name := range rendered {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		path := filepath.Join(codexHome, name)
		if err := os.WriteFile(path, []byte(rendered[name]), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

func runCLI(ctx context.Context, args []string) {
	if len(args) == 0 {
		printUsage()
		return
	}

	// Workspace root: prefer POLYFORGE_WORKSPACE_ROOT, then walk up from cwd
	// to find .polyforge.yaml (same logic as FindWorkspaceRoot).
	wsRoot := os.Getenv("POLYFORGE_WORKSPACE_ROOT")
	if wsRoot == "" {
		wsRoot = config.FindWorkspaceRoot()
	}

	// Load config.toml + .polyforge.yaml (non-fatal for version/help).
	//
	// The error is dropped on purpose — `version` and `help` must work on a
	// machine with no config at all — but the VALUE has to be made safe, which
	// it was not: EnsureMachineConfig returns (nil, err) when config.toml does
	// not parse, and the next line dereferences it. A single stray character in
	// that file therefore took down every subcommand with a nil-pointer panic,
	// including the one you run to find out what is wrong with your config
	// (`polyforge doctor`, whose whole job is to survive a broken workspace).
	mc, mcErr := config.EnsureMachineConfig()
	if mc == nil {
		fmt.Fprintf(os.Stderr, "polyforge: %s could not be loaded (%v); "+
			"continuing as if it were empty — fix that file, or move it aside\n",
			config.MachineConfigPath(), mcErr)
		mc = &config.MachineConfig{}
	}
	cfg, cfgErr := config.Load(wsRoot)

	// Build aihub client; credential precedence resolved by ResolveAPIKey /
	// EffectiveAihubURL (env override > config.toml > .polyforge.yaml >
	// built-in default, §9.5.3 + aihub#335).
	var aihubClient *client.Client
	apiKey := mc.ResolveAPIKey()
	if apiKey == "" && cfg != nil {
		apiKey = os.Getenv(cfg.AIHub.APIKeyEnv)
	}
	aihubURL, _ := config.EffectiveAihubURL(mc, workspaceAihubURL(cfg))
	// The key is now the ONLY thing that can leave the client nil:
	// EffectiveAihubURL never returns "". The URL used to be a second input to
	// the same outcome, which is why noApiKey below can state the cause flatly
	// instead of printing whichever config error happened to be lying around.
	if apiKey != "" {
		aihubClient = client.New(aihubURL, apiKey)
	}

	switch args[0] {
	case "init":
		if cfgErr != nil && aihubClient == nil {
			fmt.Fprintf(os.Stderr, "config: %v\n", cfgErr)
			os.Exit(1)
		}
		// RunInit does not guard on a nil client — it goes straight to
		// client.WhoAmI — so with a VALID .polyforge.yaml and no key it wrote
		// .polyforge/usage.md and then panicked, leaving the workspace
		// half-initialised. Refuse before touching anything.
		if aihubClient == nil {
			fatalf("%s", noAPIKey)
		}
		cli.RunInit(ctx, aihubClient, cfg, wsRoot, args[1:])
	case "doctor":
		// Deliberately NOT gated on the client: reporting that the key is
		// missing, and against which endpoint, is one of the things doctor is
		// for. checkConfig handles nil.
		cli.RunDoctor(ctx, aihubClient, cfg, wsRoot, args[1:])
	case "version":
		cli.RunVersion()
	case "get-step":
		if aihubClient == nil {
			fatalf("%s", noAPIKey)
		}
		cli.RunGetStep(ctx, aihubClient, args[1:])
	case "update-step":
		if aihubClient == nil {
			fatalf("%s", noAPIKey)
		}
		cli.RunUpdateStep(ctx, aihubClient, args[1:])
	case "dump-mcp-schemas":
		gitSHA := ""
		if len(args) > 1 {
			gitSHA = args[1]
		}
		if err := cli.RunDumpMCPSchemas(ctx, gitSHA, os.Stdout); err != nil {
			fmt.Fprintf(os.Stderr, "dump-mcp-schemas: %v\n", err)
			os.Exit(1)
		}
	case "commit":
		cli.RunCommit(ctx, args[1:])
	case "push":
		cli.RunPush(ctx, args[1:])
	case "pr":
		cli.RunPR(ctx, args[1:])
	case "artifact":
		if aihubClient == nil {
			fatalf("%s", noAPIKey)
		}
		cli.RunArtifact(ctx, aihubClient, args[1:])
	case "roles":
		// No aihubClient needed: purely local (embedded role YAMLs + mc.Roles).
		cli.RunRolesGenerate(mc, args[1:])
	case "engine":
		// No aihubClient needed: every `engine` verb is local-only (internal/engine +
		// internal/roles + git), for a future headless orchestrator (aihub#654).
		cli.RunEngine(ctx, args[1:])
	case "drain":
		// Layer 3 continuous scheduler (aihub#640). Needs a client: every scheduling
		// decision it makes is a question about server state.
		if aihubClient == nil {
			fatalf("%s", noAPIKey)
		}
		cli.RunDrain(ctx, aihubClient, wsRoot, args[1:])
	case "watch":
		// Deliberately NOT gated on the client, and it is not an oversight: watch reads a
		// local snapshot and makes no network call at all (aihub#640
		// `watch_is_light_because_of_datasource`), so requiring a credential would make the
		// observer unavailable in exactly the situations it exists for.
		cli.RunWatch(ctx, args[1:])
	case "help":
		printUsage()
	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n", args[0])
		printUsage()
		os.Exit(1)
	}
}

// noAPIKey is what every client-requiring subcommand says when it has no
// client. Since aihub#335 that has exactly one cause — EffectiveAihubURL always
// supplies an endpoint, so the key is the only missing input — which is why this
// can name the cause instead of printing whatever config error happened to be
// in scope. Those call sites used to print `config: %v` with cfgErr, and on the
// path that actually reaches them cfgErr is nil, so the message they emitted was
// the literal "config: <nil>".
const noAPIKey = "polyforge: no API key. Put it in ~/.polyforge/config.toml under\n" +
	"  [auth]\n  api_key = \"pf_k1_…\"\n" +
	"or export POLYFORGE_API_KEY. The server address is built in; you do not need to set one.\n"

// workspaceAihubURL is the .polyforge.yaml aihub.url, or "" when the workspace
// config is absent or unparseable (both non-fatal: config.toml and the built-in
// default cover the MCP server running outside a workspace).
func workspaceAihubURL(cfg *config.Config) string {
	if cfg == nil {
		return ""
	}
	return cfg.AIHub.URL
}

func fatalf(format string, a ...any) {
	fmt.Fprintf(os.Stderr, format, a...)
	os.Exit(1)
}

func printUsage() {
	fmt.Fprintln(os.Stderr, `polyforge - polyforge v1 workspace tool

Usage:
  polyforge [serve]           Start the MCP server (default)
  polyforge <command> [args]  Run a CLI command

Workspace commands:
  init                        Set up/repair workspace (usage.md, session hook, clone repos, CLAUDE.md)
  doctor [--fix] [--force-remove=<dir>[:<status>][,...]]
                              7-item health check. --fix removes orphan worktrees, but only
                              those whose work item is provably terminal (wrapped/failed/
                              cancelled); anything else is printed with its status and KEPT.
                              --force-remove overrides that for a named directory; if its
                              work item is still active the flag must also carry that
                              status. See "polyforge doctor --help" for the detail.
  version                     Print version

Schema export:
  dump-mcp-schemas [<git-sha>]   Print all registered MCP tool schemas as contract JSON

Step management (machine-user):
  get-step [--wi-id=<id>]     Get current step
  update-step --step-id=<id> --status=<status>  Update step status

Git helpers (machine-user):
  commit [--wi-id=<id>] [--message=<msg>]  git commit in worktree
  push   [--wi-id=<id>]                    git push in worktree
  pr     [--wi-id=<id>] --title=<t>        gh pr create in worktree

Artifact viewer:
  artifact view <memory_id>   Fetch spec/plan HTML and open in browser

Role/tier agent generation (aihub#642):
  roles generate <pi|codex> --out <dir> [--preset=<name>]
                              Render per-role agent files (pf-<role>.md for pi,
                              step-<role>.toml for codex) from
                              internal/roles/definitions/*.yaml and this
                              machine's ~/.polyforge/config.toml [roles.tiers]
                              candidate lists. Claude Code's step-<role>.md
                              files are generated at build time instead
                              (committed via "go generate ./internal/roles/...")
                              -- this subcommand never touches them.
                              --preset generates from a named tier table
                              instead of the machine's configured selection.

Tier-table presets (aihub#673): a preset is a NAMED SNAPSHOT of the whole
tier->model table, and selecting one SWAPS the table rather than merging with
it. All three readers honour the same selection -- "roles generate", the
serve-startup codex profile generation, and "polyforge drain" -- so one machine
cannot resolve different models depending on which entry point ran:
    [roles]
    preset = "frugal"              # this machine's default
    [roles.presets.frugal.tiers]
    default = [{ harness = "pi", model = "claude-haiku-4-5" }]
An unknown preset name is refused, never silently ignored.

Codex profile auto-generation (aihub#655, serve startup only, not a
subcommand): when the codex CLI is on PATH, every "polyforge serve" boot
(re)writes $CODEX_HOME/step-<role>.config.toml (default ~/.codex), one per
role, containing model/sandbox_mode/developer_instructions -- the codex
config-profile shape codex's own "-p <name>" / "--profile <name>" flag
loads. This is a different file (and a different, actually-scanned
directory) than "roles generate codex --out <dir>" above writes; see
internal/roles/render_codex.go's RenderCodexProfiles for why both exist.

Engine (aihub#654, local-only, for a future headless orchestrator):
  engine startup --workspace-root=<dir> --worktree-root=<dir> --scenario-url=<url>
                 --wi-type=<type> [--project=<name>]
                              Resolve scenario path (owner-qualified, legacy-fallback),
                              pin its HEAD sha, resolve+scan the wi_type template into
                              steps, expand each step's @include:/level: pairs, and write
                              <worktree-root>/.pf_meta.json. Prints scenario_path,
                              legacy_fallback, sha, template_source and the step list.
  engine resolve-role --step-id=<id> [--declared-role=<name>]
                              Run the 3-tier role fallback (declared -> catalog ->
                              heuristic) against the real internal/roles catalog; never
                              bottoms out at "executor". Prints role, tier, read_only,
                              source, and unknown_declared_role (set only when
                              --declared-role was given but unknown to the catalog).
  engine parse-review [--file=<path>]
                              Parse a REVIEW_RESULT marker (last one wins if several;
                              WARN if none) from --file, or stdin if omitted. Prints
                              result.
  engine bracket-plan --step-id=<id> --status=<completed|failed> --step-attempt-id=<sa>
                       [--next-step-id=<id>] [--next-step-attempt-id=<sa>]
                       [--supports-next-step] [--artifact-summary=<text>]
                       [--error-type=<type>]
                              Plan the pf_update_step call sequence for completing/failing
                              a step (fused single call when the connected server supports
                              next_step, else the degraded two-call form). Prints a JSON
                              array of calls.
  engine cleanup-worktrees --workspace-root=<dir> --worktrees=<json-map-repo-to-path>
                              Remove each repo's worktree (git worktree remove --force,
                              run from <workspace-root>/.repo/<repo-name>, the repo's
                              main clone, so a worktree already deleted by an
                              interrupted prior cleanup is still pruned), then the
                              shared parent directory once, after the loop,
                              unconditionally (even if a per-repo removal failed).
                              Best-effort: always exits 0, reporting what succeeded in
                              "removed" and every failure in "errors" (one entry per
                              failing repo, plus "(parent)" if the shared-parent
                              removal itself failed). Prints removed, errors.

Layer 3 continuous scheduling (aihub#640):
  drain --project=<name> [--all] [--plan] [--max-parallel=<n>]
        [--max-rounds=<n>] [--max-work-items=<n>] [--channel=<h[/model],...>]
        [--preset=<name>] [--detach] [--json]
                              Repeatedly select the work items that are executable
                              right now (queued, rhs=false, no unfinished blocking
                              dependency, in scope), run them across rounds, and stop
                              with a terminal state. Exit codes: 0 COMPLETED,
                              10 IDLE, 11 BLOCKED_EXTERNAL, 12 FAILED.
                              --plan reports what WOULD run and claims nothing.
                              --preset picks the tier->model table to dispatch with
                              (see [roles.presets] below); --channel still wins
                              wherever it names a model.
                              --detach runs it in the background (setsid; there is no
                              systemd here) and prints run id + pid + log path.
  drain --stop [--run=<id>]   Stop the running drain on this machine -- the most
                              recent run, or the one named by --run. Sends SIGTERM,
                              the same signal Ctrl-C sends, so the run takes its
                              normal graceful-cancellation path and writes a proper
                              terminal snapshot. It NEVER escalates to SIGKILL:
                              that would skip the final snapshot write and leave the
                              run looking like a crash.
                              Work items whose step was in flight are left CLAIMED
                              and holding their locks (unchanged from Ctrl-C); --stop
                              names them so they can be recovered.
                              Deliberately a drain flag, not a top-level "halt":
                              /pf-stop is the WORK-ITEM lifecycle verb
                              (--pause/--wrap/--fail) and must not be shadowed.
  watch [--run=<id>] [--follow] [--list] [--json]
                              Show what a running drain is doing. Reads only that
                              run's local snapshot: zero network, so it never hangs
                              on a slow server. This is the PROCESS's view of one
                              run on this machine, not the project's -- for the
                              repository view use /pf-status.

Config files (§9.5.3):
  ~/.polyforge/config.toml   Machine-level config (machine_id, [auth] api_key)
  .polyforge.yaml            Workspace config (aihub.url, scenario, projects)

  config.toml [auth] example:
    machine_id = "<auto-generated UUID>"
    [auth]
    api_key = "your-key-here"
    # OR: api_key_env = "POLYFORGE_API_KEY"

  The api_key is the ONLY thing you have to write by hand. The team's aihub
  endpoint is compiled into this binary, so no document has to carry it and no
  copy of it can go stale on your machine; "polyforge doctor" prints the
  endpoint in use and where it came from. Add a [server] url only to point at
  a different aihub:
    [server]
    url = "http://your-own-aihub:8080"

Environment (overrides config.toml):
  POLYFORGE_WORKSPACE_ROOT   Workspace root (default: cwd)
  POLYFORGE_API_KEY          API key override (highest priority)
  POLYFORGE_AIHUB_URL        aihub URL override (else: [server] url,
                             .polyforge.yaml aihub.url, then the built-in
                             default)
  POLYFORGE_MACHINE_ID       Machine ID override (CI containers)
  POLYFORGE_WORK_ITEM_ID     Active wi ID (used by get-step/update-step/commit/push/pr)
  CI                         Set to "true" in CI environments
`[1:])
}
