#!/usr/bin/env bash
# Test suite for hooks/pf-commit-guard. Feeds synthetic PreToolUse payloads on stdin and
# asserts on the emitted JSON: banned attribution strings must DENY, legit lookalikes must
# pass (no output). Assert-based, no framework — mirrors tests/pf-skill-router.test.sh.
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
guard="$here/../hooks/pf-commit-guard"
[ -x "$guard" ] || { echo "FAIL: guard not executable" >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "SKIP: python3 unavailable"; exit 0; }
command -v jq >/dev/null 2>&1 && HAVE_JQ=1 || HAVE_JQ=0
fails=0

run() { printf '%s' "$1" | "$guard" 2>/dev/null; }
has() { case "$1" in *"$2"*) return 0;; *) return 1;; esac; }

# JSON payload builders (jq-escaped when available, else a minimal escaper for quotes/backslash)
esc() {
  if [ "$HAVE_JQ" -eq 1 ]; then printf '%s' "$1" | jq -Rs .; else
    printf '"%s"' "$(printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g')"; fi
}
p_commit() { printf '{"tool_name":"mcp__plugin_polyforge_polyforge__pf_commit","tool_input":{"message":%s}}' "$(esc "$1")"; }
p_pr()     { printf '{"tool_name":"mcp__plugin_polyforge_polyforge__pf_pr","tool_input":{"title":"ok","body":%s}}' "$(esc "$1")"; }
p_wrap()   { printf '{"tool_name":"mcp__plugin_polyforge_polyforge__pf_wrap","tool_input":{"pr_title":%s,"pr_body":"ok"}}' "$(esc "$1")"; }
p_bash()   { printf '{"tool_name":"Bash","tool_input":{"command":%s}}' "$(esc "$1")"; }
# pf_ship (aihub#286) fuses commit+push+PR, so one call carries all three text fields.
p_ship_msg()   { printf '{"tool_name":"mcp__plugin_polyforge_polyforge__pf_ship","tool_input":{"message":%s,"pr_title":"ok","pr_body":"ok"}}' "$(esc "$1")"; }
p_ship_title() { printf '{"tool_name":"mcp__plugin_polyforge_polyforge__pf_ship","tool_input":{"message":"ok","pr_title":%s,"pr_body":"ok"}}' "$(esc "$1")"; }
p_ship_body()  { printf '{"tool_name":"mcp__plugin_polyforge_polyforge__pf_ship","tool_input":{"message":"ok","pr_title":"ok","pr_body":%s}}' "$(esc "$1")"; }

# block_ck: expect a deny decision for the given payload
block_ck() {
  local out; out="$(run "$2")"
  if has "$out" '"permissionDecision": "deny"'; then echo "  PASS: blocks $1";
  else echo "  FAIL: should block $1 (got: ${out:-<empty>})" >&2; fails=$((fails+1)); fi
}
# pass_ck: expect NO output (call proceeds)
pass_ck() {
  local out; out="$(run "$2")"
  if [ -z "$out" ]; then echo "  PASS: allows $1";
  else echo "  FAIL: should allow $1 (got: $out)" >&2; fails=$((fails+1)); fi
}

echo "== MUST-BLOCK: banned attribution strings =="
block_ck "Co-Authored-By trailer"        "$(p_commit 'fix cache bug

Co-Authored-By: Claude <noreply@anthropic.com>')"
block_ck "bare Claude in subject"         "$(p_commit 'tweak per Claude review')"
block_ck "Claude Code phrase"             "$(p_commit 'built with Claude Code')"
block_ck "Anthropic mention"              "$(p_commit 'sync with Anthropic API change')"
block_ck "standalone AI"                  "$(p_commit 'this used AI to refactor')"
block_ck "LLM acronym"                    "$(p_commit 'add LLM prompt template')"
block_ck "AI-assisted phrase"             "$(p_commit 'AI-assisted cleanup')"
block_ck "model name claude-opus-4"       "$(p_commit 'generated by claude-opus-4-8')"
block_ck "model name sonnet"              "$(p_commit 'reviewed by sonnet')"
block_ck "model name opus"                "$(p_commit 'opus wrote this helper')"
block_ck "model name haiku"               "$(p_commit 'haiku drafted the tests')"
block_ck "Generated with"                 "$(p_pr   'Generated with the assistant')"
block_ck "Generated by"                   "$(p_pr   'Generated by a bot')"
block_ck "banned in pr_title (wrap)"      "$(p_wrap 'Claude-authored change')"
block_ck "git commit -m banned"           "$(p_bash 'git commit -m "Co-Authored-By: Claude"')"
block_ck "gh pr create banned"            "$(p_bash 'gh pr create --title "AI-assisted fix" --body x')"

echo ""
echo "== pf_ship fuses commit+push+PR, so all three of its text fields are scanned =="
# aihub#286: a guard keyed on tool name is a property of the ENTRY POINT, not of the
# git operation. Fusing three guarded tools into a new one starts it unguarded, which
# is silent — the commit still lands, just without the attribution check.
block_ck "banned in ship message"  "$(p_ship_msg   'Co-Authored-By: Claude')"
block_ck "banned in ship pr_title" "$(p_ship_title 'AI-assisted refactor')"
block_ck "banned in ship pr_body"  "$(p_ship_body  'Generated with Claude Code')"
pass_ck  "clean ship message"      "$(p_ship_msg   'fix race in reconnect logic')"
block_ck "Codex pf_ship banned"    '{"tool_name":"mcp__polyforge__pf_ship","tool_input":{"message":"Co-Authored-By: Claude","pr_title":"ok","pr_body":"ok"}}'
block_ck "Copilot pf_ship banned"  '{"tool_name":"polyforge-pf_ship","tool_input":{"message":"ok","pr_title":"ok","pr_body":"AI-assisted fix"}}'

echo ""
echo "== Codex tool-name prefix (mcp__polyforge__*) must guard identically =="
block_ck "Codex pf_commit banned"     '{"tool_name":"mcp__polyforge__pf_commit","tool_input":{"message":"Co-Authored-By: Claude"}}'
block_ck "Codex pf_pr banned"         '{"tool_name":"mcp__polyforge__pf_pr","tool_input":{"title":"ok","body":"AI-assisted fix"}}'
block_ck "Codex pf_wrap banned"       '{"tool_name":"mcp__polyforge__pf_wrap","tool_input":{"pr_title":"reviewed by sonnet","pr_body":"ok"}}'
pass_ck  "Codex unrelated tool inert" '{"tool_name":"mcp__polyforge__pf_get_work_item","tool_input":{"work_item_id":"AI-assisted"}}'
pass_ck  "Codex clean commit"         '{"tool_name":"mcp__polyforge__pf_commit","tool_input":{"message":"fix race in reconnect logic"}}'

echo ""
echo "== MUST-PASS: legit lookalikes and clean text (zero false positives) =="
pass_ck "maintain/contain/detail"   "$(p_commit 'maintain the contained detail in the handler')"
pass_ck "email + domain"            "$(p_commit 'validate email against the allowed domain')"
pass_ck "retain/certain/chains"     "$(p_commit 'retain certain chains across restarts')"
pass_ck "explain + again"           "$(p_commit 'explain the retry path and try again')"
pass_ck "available/fail/wait"       "$(p_commit 'wait until available, then fail fast')"
pass_ck "plain human commit"        "$(p_commit 'fix race condition in reconnect logic')"
pass_ck "clean pr body"            "$(p_pr   'This change retains backward compatibility and adds detail to errors.')"
pass_ck "clean wrap title"         "$(p_wrap 'Refactor the scheduler queue draining')"
pass_ck "non-git Bash inert"       "$(p_bash 'ls -la && rg AI-assisted README.md')"  # not git/gh -> not scanned
pass_ck "unrelated MCP tool inert" '{"tool_name":"mcp__plugin_polyforge_polyforge__pf_get_work_item","tool_input":{"work_item_id":"AI-assisted"}}'
pass_ck "empty message inert"      "$(p_commit '')"
pass_ck "no python field inert"    '{"tool_name":"mcp__plugin_polyforge_polyforge__pf_commit","tool_input":{}}'

echo ""
echo "== aihub#272 half 1: text DESTINED for git is still blocked =="
# This half has no discriminating power on its own — every case here was blocked
# before the fix too. It is the anchor that stops the fix from degenerating into
# "widen the allow-list": half 2 below is the half that was red.
block_ck "git commit -m carries a trailer" "$(p_bash 'git commit -m "fix thing

Co-Authored-By: Claude <noreply@anthropic.com>"')"
block_ck "git commit -am clustered short flag" "$(p_bash 'git commit -am "generated by a model"')"
block_ck "git commit --message= form"      "$(p_bash 'git commit --message="AI-assisted refactor"')"
block_ck "git commit -m glued to its value" "$(p_bash 'git commit -m"reviewed by sonnet"')"
block_ck "git merge -m attribution"        "$(p_bash 'git merge -m "Co-Authored-By: Claude" origin/main')"
block_ck "git tag -m attribution"          "$(p_bash 'git tag -a v1 -m "written by Claude"')"
block_ck "gh pr create --body attribution" "$(p_bash 'gh pr create --title ok --body "Generated with Claude Code"')"
block_ck "gh pr create --title attribution" "$(p_bash 'gh pr create --title "AI-assisted fix" --body ok')"
# The message text is not in a flag value at all — it is assembled by the shell.
# Narrowing the scan to flag values must NOT open this: an extracted value that
# contains a shell expansion is not something the guard can vouch for, so it
# falls back to scanning the whole command.
block_ck "message assembled in a shell variable" "$(p_bash 'MSG="Co-Authored-By: Claude"; git commit -m "$MSG"')"
block_ck "heredoc message on stdin"        "$(p_bash 'git commit -F - <<EOF
fix the thing

Co-Authored-By: Claude
EOF')"

# -F <file>: the message lives in a file, so the file must be read and scanned.
MSGDIR="$(mktemp -d)"
printf 'fix the thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n' > "$MSGDIR/dirty.txt"
printf 'fix the thing\n\nthe reason it was broken\n' > "$MSGDIR/clean.txt"
block_ck "git commit -F <file> with attribution" "$(p_bash "git commit -F $MSGDIR/dirty.txt")"
pass_ck  "git commit -F <file> that is clean"    "$(p_bash "git commit -F $MSGDIR/clean.txt")"
# A named message file the guard cannot read is not a clean bill of health: it
# usually means the file is about to be created by an earlier part of the same
# command line, which is exactly where the text would be hiding.
block_ck "git commit -F <file> written by the same command" \
  "$(p_bash "printf 'Co-Authored-By: Claude\\n' > $MSGDIR/later.txt && git commit -F $MSGDIR/later.txt")"
rm -rf "$MSGDIR"

echo ""
echo "== aihub#272 half 2: a pattern that merely MENTIONS the literal must pass =="
# THE point of aihub#272. The guard matched the whole Bash command string, so it
# could not tell text being WRITTEN into git from a pattern used to SEARCH git
# for that same text — and denied the only automated check that the <undercover>
# rule has. Every case below was DENIED before the fix; each is read-only.
pass_ck "audit: loop over commits and grep each" \
  "$(p_bash "for c in \$(git rev-list origin/main..HEAD); do git log -1 --format=%B \$c; done | grep -icE 'claude|co-authored' # audit each commit")"
pass_ck "audit: gh pr view body | grep" \
  "$(p_bash "gh pr view 42 --json body -q .body | grep -iE 'co-authored-by|generated with'")"
pass_ck "audit: git log | grep for the trailer" \
  "$(p_bash "git log -1 --format=%B | grep -iE 'co-authored|generated with|claude'")"
pass_ck "audit: git show -s | grep" \
  "$(p_bash 'git show -s --format=%B HEAD | grep -qi claude && echo DIRTY || echo CLEAN')"
pass_ck "audit: grep -Ef pattern file over the log" \
  "$(p_bash 'git log -20 --format=%B | grep -Ef /tmp/pat.txt')"
# A path argument that merely contains a watched literal (.claude-plugin/) in a
# command that also contains the word "commit". Verbatim shape that this guard
# denied while the fix for it was being written.
pass_ck "audit: path segment .claude-plugin in a log command" \
  "$(p_bash 'git log --oneline -20 -p -- .claude-plugin/marketplace.json | grep -E "^commit |catalog_revision"')"

echo ""
echo "== aihub#272 half 2b: 'AI' as an ordinary word is not an attribution =="
# The guard denied a PR body for containing "Siteboon AI B.V." — the legal name
# of an upstream copyright holder, quoted while doing AGPL s7 attribution
# compliance. Naming the copyright holder IS the task; there is no rewording
# around it. The real carrier of AI attribution is a trailer, not prose.
pass_ck "legal name: Siteboon AI B.V." \
  "$(p_pr 'Preserve the upstream notice naming Siteboon AI B.V. as the copyright holder (LICENSE:689-693).')"
pass_ck "technical prose: AI gateway" \
  "$(p_commit 'route inference through the AI gateway instead of the proxy')"
pass_ck "technical prose: AI-native, AIops, OpenAI" \
  "$(p_commit 'add an OpenAI-compatible endpoint for the AIops dashboard')"
# ...but a bare AI inside a trailer block is still an attribution, and the
# narrowing must not reach it. This is the negative control for half 2b: without
# it, deleting the `ai` alternative outright would satisfy every case above.
block_ck "bare AI in a trailer block" "$(p_commit 'fix the router lookup

AI: yes')"
block_ck "bare AI trailer in a pr_body" "$(p_pr 'This narrows the guard.

Assisted-By: AI')"

echo ""
echo "== fail-open on bad payload =="
pass_ck "unparseable payload"      'not json at all'

echo ""
echo "== git-workflow rules: hermetic fixture (worktree gate / protected push / finishing ops) =="
FIXTURE="$(mktemp -d)"
cleanup_fixture() { rm -rf "$FIXTURE"; }
trap cleanup_fixture EXIT

mkdir -p "$FIXTURE/.repo/aihub" "$FIXTURE/.repo/polyforge-coding" \
         "$FIXTURE/pf.aihub-1/aihub" "$FIXTURE/pf.B-2/aihub" "$FIXTURE/.polyforge/state"
cat > "$FIXTURE/.polyforge.yaml" <<EOF
version: 1
scenario: coding
projects:
    aihub:
        repos:
            - name: aihub
              url: git@github.com:GMISWE/ieops-aihub.git
            - name: marketplace
              url: git@github.com:GMISWE/GMI-marketplace.git
        description: ""
EOF
git init -q "$FIXTURE/.repo/aihub"
git init -q "$FIXTURE/pf.aihub-1/aihub"

# Credential state files carry a `worktrees` map of absolute paths — that map is
# what ties a live wi to a pf.<...> dir. wi_a owns pf.aihub-1, wi_b owns pf.B-2.
CRED_A="$FIXTURE/.polyforge/state/wi_a.json"
CRED_B="$FIXTURE/.polyforge/state/wi_b.json"
printf '{"wi_id":"wi_a","worktrees":{"aihub":"%s"}}\n' "$FIXTURE/pf.aihub-1/aihub" > "$CRED_A"
printf '{"wi_id":"wi_b","worktrees":{"aihub":"%s"}}\n' "$FIXTURE/pf.B-2/aihub"    > "$CRED_B"

p_bash_c() { printf '{"tool_name":"Bash","tool_input":{"command":%s},"cwd":"/tmp"}' "$(esc "$1")"; }

block_ck "worktree gate: commit in .repo/aihub" \
  "$(p_bash_c "git -C $FIXTURE/.repo/aihub commit -m msg")"
pass_ck "worktree gate: non-project .repo/polyforge-coding" \
  "$(p_bash_c "git -C $FIXTURE/.repo/polyforge-coding commit -m msg")"
pass_ck "worktree gate: claimed pf.* worktree" \
  "$(p_bash_c "git -C $FIXTURE/pf.aihub-1/aihub commit -m msg")"

block_ck "protected branch push: origin main" \
  "$(p_bash_c 'git push origin main')"
block_ck "protected branch push: fully-qualified refs/heads/dev" \
  "$(p_bash_c 'git push origin main:refs/heads/dev')"
pass_ck "protected branch push: task branch" \
  "$(p_bash_c 'git push origin polyforge/abc')"
pass_ck "protected branch push: fully-qualified non-protected ref" \
  "$(p_bash_c 'git push origin feat:refs/heads/mybranch')"

# --- Rule 3: owning credential present (wi_a owns pf.aihub-1) -> DENY finishing ops ---
block_ck "finishing ops: merge in pf.aihub-1 (owning cred present)" \
  "$(p_bash_c "git -C $FIXTURE/pf.aihub-1/aihub merge origin/main")"
block_ck "finishing ops: branch -D in pf.aihub-1 (owning cred present)" \
  "$(p_bash_c "git -C $FIXTURE/pf.aihub-1/aihub branch -D old-branch")"
block_ck "finishing ops: worktree remove pf.aihub-1 (owning cred present)" \
  "$(p_bash_c "git worktree remove $FIXTURE/pf.aihub-1/aihub")"
block_ck "attribution via git merge -m (independent of Rule 3)" \
  "$(p_bash_c "git -C $FIXTURE/pf.aihub-1/aihub merge -m \"Co-Authored-By: Claude\" origin/main")"

# --- Multi-wi: removing pf.B-2 must ALLOW once B's cred is gone, even though A's
#     cred still exists. (The old any-*.json check wrongly denied this.) ---
rm -f "$CRED_B"
pass_ck "multi-wi: worktree remove pf.B-2 after wi_b cred gone (wi_a still present)" \
  "$(p_bash_c "git worktree remove $FIXTURE/pf.B-2/aihub")"
block_ck "multi-wi: pf.aihub-1 still denied while wi_a cred present" \
  "$(p_bash_c "git worktree remove $FIXTURE/pf.aihub-1/aihub")"

# --- Transition: delete pf.aihub-1's OWN credential -> the SAME command ALLOWS ---
rm -f "$CRED_A"
pass_ck "transition: worktree remove pf.aihub-1 after wi_a cred gone (post-wrap)" \
  "$(p_bash_c "git worktree remove $FIXTURE/pf.aihub-1/aihub")"
pass_ck "transition: merge in pf.aihub-1 after wi_a cred gone (post-wrap)" \
  "$(p_bash_c "git -C $FIXTURE/pf.aihub-1/aihub merge origin/main")"

# --- Sidecar-lingers: only a .chain.json remains (wrap deletes the credential but
#     leaves the chain sidecar). Must be treated as post-wrap -> ALLOW. ---
printf '{"wi_id":"wi_x","step":"done"}\n' > "$FIXTURE/.polyforge/state/wi_x.chain.json"
pass_ck "sidecar: worktree remove pf.aihub-1 with only wi_x.chain.json present" \
  "$(p_bash_c "git worktree remove $FIXTURE/pf.aihub-1/aihub")"

cleanup_fixture
trap - EXIT

# ---------------------------------------------------------------------------
# Hop 2: the REGISTERED MATCHER must actually route these tools to the guard.
#
# Every case above feeds the guard script directly, which proves what the script
# does once it runs — and proves nothing about whether the harness ever runs it.
# The matcher regexes in hooks.json / codex-hooks.json / copilot-hooks.json are a
# second, independent hop, and a tool missing from them is guarded by a script
# that is never invoked: a fully green suite over a dead gate. aihub#286 added
# pf_ship and hit exactly that, so the contract gets an assertion per hop.
#
# The unrelated-tool case below is the negative control: without it, a matcher
# widened to ".*" would satisfy every positive assertion here.
# ---------------------------------------------------------------------------
echo ""
echo "== registered matchers route the guarded tools to this hook (all 3 harnesses) =="
matcher_out="$(python3 - "$here/.." <<'PY'
import json, os, re, sys

root = sys.argv[1]
# file -> (tool names that MUST match, tool names that must NOT match)
cases = {
    "hooks/hooks.json": (
        ["mcp__plugin_polyforge_polyforge__pf_" + t for t in ("commit", "pr", "wrap", "ship")] + ["Bash"],
        ["mcp__plugin_polyforge_polyforge__pf_get_work_item"],
    ),
    "codex-hooks.json": (
        ["mcp__polyforge__pf_" + t for t in ("commit", "pr", "wrap", "ship")] + ["Bash"],
        ["mcp__polyforge__pf_get_work_item"],
    ),
    "copilot-hooks.json": (
        ["polyforge-pf_" + t for t in ("commit", "pr", "wrap", "ship")] + ["bash"],
        ["polyforge-pf_get_work_item"],
    ),
}

def guard_matchers(node):
    """Every `matcher` whose subtree invokes pf-commit-guard."""
    found = []
    if isinstance(node, dict):
        if "matcher" in node and "pf-commit-guard" in json.dumps(node):
            found.append(node["matcher"])
        for v in node.values():
            found += guard_matchers(v)
    elif isinstance(node, list):
        for v in node:
            found += guard_matchers(v)
    return found

fails = 0
for rel, (must, must_not) in cases.items():
    path = os.path.join(root, rel)
    with open(path) as fh:
        doc = json.load(fh)
    matchers = guard_matchers(doc)
    if not matchers:
        print(f"  FAIL: {rel} registers no matcher for pf-commit-guard")
        fails += 1
        continue
    for tool in must:
        if not any(re.search(m, tool) for m in matchers):
            print(f"  FAIL: {rel} matcher {matchers} does not route {tool} to pf-commit-guard")
            fails += 1
        else:
            print(f"  PASS: {rel} routes {tool}")
    for tool in must_not:
        if any(re.search(m, tool) for m in matchers):
            print(f"  FAIL: {rel} matcher {matchers} is too broad — it also routes {tool}")
            fails += 1
        else:
            print(f"  PASS: {rel} leaves {tool} unrouted")
sys.exit(1 if fails else 0)
PY
)"
matcher_rc=$?
printf '%s\n' "$matcher_out"
[ "$matcher_rc" -eq 0 ] || fails=$((fails+1))

echo ""
[ "$fails" -eq 0 ] && { echo "ALL PASS"; exit 0; } || { echo "$fails FAILED" >&2; exit 1; }
