#!/usr/bin/env bash
# Test suite for hooks/pf-commit-guard. Feeds synthetic PreToolUse payloads on stdin and
# asserts on the emitted JSON: banned attribution strings must DENY, legit lookalikes must
# pass (no output). Assert-based, no framework — mirrors pf-superpowers-bridge.test.sh.
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
guard="$here/../hooks/pf-commit-guard"
[ -x "$guard" ] || { echo "FAIL: guard not executable" >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "SKIP: python3 unavailable"; exit 0; }
command -v jq >/dev/null 2>&1 && HAVE_JQ=1 || HAVE_JQ=0
fails=0

run() { printf '%s' "$1" | "$guard" 2>/dev/null; }
has() { case "$1" in *"$2"*) return 0;; *) return 1;; esac; }

# JSON payload builders (jq-escaped when available, else a minimal escaper for quotes/backslash)
esc() {
  if [ "$HAVE_JQ" -eq 1 ]; then printf '%s' "$1" | jq -Rs .; else
    printf '"%s"' "$(printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g')"; fi
}
p_commit() { printf '{"tool_name":"mcp__plugin_polyforge_polyforge__pf_commit","tool_input":{"message":%s}}' "$(esc "$1")"; }
p_pr()     { printf '{"tool_name":"mcp__plugin_polyforge_polyforge__pf_pr","tool_input":{"title":"ok","body":%s}}' "$(esc "$1")"; }
p_wrap()   { printf '{"tool_name":"mcp__plugin_polyforge_polyforge__pf_wrap","tool_input":{"pr_title":%s,"pr_body":"ok"}}' "$(esc "$1")"; }
p_bash()   { printf '{"tool_name":"Bash","tool_input":{"command":%s}}' "$(esc "$1")"; }

# block_ck: expect a deny decision for the given payload
block_ck() {
  local out; out="$(run "$2")"
  if has "$out" '"permissionDecision": "deny"'; then echo "  PASS: blocks $1";
  else echo "  FAIL: should block $1 (got: ${out:-<empty>})" >&2; fails=$((fails+1)); fi
}
# pass_ck: expect NO output (call proceeds)
pass_ck() {
  local out; out="$(run "$2")"
  if [ -z "$out" ]; then echo "  PASS: allows $1";
  else echo "  FAIL: should allow $1 (got: $out)" >&2; fails=$((fails+1)); fi
}

echo "== MUST-BLOCK: banned attribution strings =="
block_ck "Co-Authored-By trailer"        "$(p_commit 'fix cache bug

Co-Authored-By: Claude <noreply@anthropic.com>')"
block_ck "bare Claude in subject"         "$(p_commit 'tweak per Claude review')"
block_ck "Claude Code phrase"             "$(p_commit 'built with Claude Code')"
block_ck "Anthropic mention"              "$(p_commit 'sync with Anthropic API change')"
block_ck "standalone AI"                  "$(p_commit 'this used AI to refactor')"
block_ck "LLM acronym"                    "$(p_commit 'add LLM prompt template')"
block_ck "AI-assisted phrase"             "$(p_commit 'AI-assisted cleanup')"
block_ck "model name claude-opus-4"       "$(p_commit 'generated by claude-opus-4-8')"
block_ck "model name sonnet"              "$(p_commit 'reviewed by sonnet')"
block_ck "model name opus"                "$(p_commit 'opus wrote this helper')"
block_ck "model name haiku"               "$(p_commit 'haiku drafted the tests')"
block_ck "Generated with"                 "$(p_pr   'Generated with the assistant')"
block_ck "Generated by"                   "$(p_pr   'Generated by a bot')"
block_ck "banned in pr_title (wrap)"      "$(p_wrap 'Claude-authored change')"
block_ck "git commit -m banned"           "$(p_bash 'git commit -m "Co-Authored-By: Claude"')"
block_ck "gh pr create banned"            "$(p_bash 'gh pr create --title "AI-assisted fix" --body x')"

echo ""
echo "== MUST-PASS: legit lookalikes and clean text (zero false positives) =="
pass_ck "maintain/contain/detail"   "$(p_commit 'maintain the contained detail in the handler')"
pass_ck "email + domain"            "$(p_commit 'validate email against the allowed domain')"
pass_ck "retain/certain/chains"     "$(p_commit 'retain certain chains across restarts')"
pass_ck "explain + again"           "$(p_commit 'explain the retry path and try again')"
pass_ck "available/fail/wait"       "$(p_commit 'wait until available, then fail fast')"
pass_ck "plain human commit"        "$(p_commit 'fix race condition in reconnect logic')"
pass_ck "clean pr body"            "$(p_pr   'This change retains backward compatibility and adds detail to errors.')"
pass_ck "clean wrap title"         "$(p_wrap 'Refactor the scheduler queue draining')"
pass_ck "non-git Bash inert"       "$(p_bash 'ls -la && rg AI-assisted README.md')"  # not git/gh -> not scanned
pass_ck "unrelated MCP tool inert" '{"tool_name":"mcp__plugin_polyforge_polyforge__pf_get_work_item","tool_input":{"work_item_id":"AI-assisted"}}'
pass_ck "empty message inert"      "$(p_commit '')"
pass_ck "no python field inert"    '{"tool_name":"mcp__plugin_polyforge_polyforge__pf_commit","tool_input":{}}'

echo ""
echo "== fail-open on bad payload =="
pass_ck "unparseable payload"      'not json at all'

echo ""
[ "$fails" -eq 0 ] && { echo "ALL PASS"; exit 0; } || { echo "$fails FAILED" >&2; exit 1; }
