-- +goose Up

-- aihub#708 Batch 2A: WI-owned workflow persistence — the storage half of the
-- "work_items.steps JSONB plus steps_version points to the current generation
-- and an append-only snapshot/history preserves old ones" decision (spec D4).
--
-- DEPLOY ORDER: strictly additive (two new columns on work_items with safe
-- defaults, five new tables), so apply BEFORE the binary that reads them and
-- ROLLBACK of the binary is safe — the old binary never names these tables.
--
-- The whole Up section is idempotent (ADD COLUMN IF NOT EXISTS, CREATE ...
-- IF NOT EXISTS, constraints inline), mirroring 0043's replay-hazard rule
-- (aihub#444): a test replaying it against a migrated database is a no-op.
--
-- ─── The shape, and why each table exists ────────────────────────────────────
--
-- work_items.steps / steps_version  the CURRENT generation pointer.
--   steps is the pinned flow JSON (exact skill_id+version per step); NULL and
--   steps_version=0 mean "no workflow" — the legacy path, byte-identical to
--   before this migration. steps_version is the CAS token a revision compares
--   against (like projects.members_version) AND the foreign key side that
--   names the current row in wi_workflow_generations.
--
-- wi_workflow_generations  the APPEND-ONLY immutable generations. A revision
--   never UPDATEs a generation row: it INSERTs steps_version+1 and moves the
--   pointer. Each row also freezes the server-derived per-step grants (the
--   trusted ExecutionContext half of internal/workflow), the per-step resolved
--   semantic metadata (capabilities + interactive flag, NOT skill content),
--   and the validation digest — so results and approvals can be validated
--   without re-reading the registry, and a generation stays interpretable even
--   if a grant later changes its policy.
--
--   What is deliberately NOT here: skill bundles, contracts, or any skill
--   CONTENT. A generation stores references (skill_id, version) and the
--   derived metadata only. A work item's workflow must never become a second
--   publication channel for private skill bodies (spec D3: "WI visibility
--   never widens skill content").
--
-- wi_workflow_invocations  the controller-MINTED step attempts. step_attempt_id
--   is generated by the SERVER at /workflow/start, never chosen by the caller,
--   so a worker cannot pre-guess the identity a result must echo (spec D7:
--   "Shared control enforces current attempt epoch, flow version, step
--   instance and step attempt"). producer_id is likewise server-assigned: the
--   producer-independence rule in the pure policy (review/verification gates
--   must not share a producer with the writes they gate) needs per-invocation
--   producer identities that no client can forge.
--
-- wi_workflow_results  the recorded worker outputs, one row per terminal
--   result, keyed by the invocation it answers. No code path UPDATEs or
--   DELETEs a result row; supersession is expressed by a NEWER result row.
--   This is the workflow's step history — the ONLY one a workflow work item
--   has. Nothing is copied into the legacy wi_step_completions (whose readers
--   filter by work_item_id alone and would read a superseded generation's
--   rows as current scenario history); every row here carries its full flow
--   identity, so no superseded generation can masquerade.
--
-- wi_workflow_approvals  the human decisions. One row binds the exact
--   (artifact id, version, hash) triple AND the (work_item, steps_version,
--   step_id) identity of the step whose output is being approved, plus the
--   AUTHENTICATED human actor — never an actor string the request carried
--   (spec D7: "no worker forged actor"). Uniqueness is on that whole binding,
--   so re-approving the same triple is idempotent and a REJECTED row blocks
--   an APPROVED row for the same artifact.
--
-- wi_workflow_repair_episodes  the controller-authorized recoveries, in both
--   shapes the pure policy defines (internal/workflow):
--   kind='retry'    the bounded single retry of one failed invocation
--                   (RepairAuthorization): D9's infrastructure-failure
--                   fallback — "record new invocation before retry".
--   kind='episode'  the full review-FAIL recovery (RepairEpisode): a repair
--                   producer, a fresh verification and a fresh independent
--                   review, each an invocation bound to the episode.
--   Both are OPENED explicitly by the authenticated /workflow/repair route
--   (never by a result or a start), are bounded by the pure policy, and are
--   closed ONLY when their bounded set is complete: a retry when its one
--   invocation has a recorded result, an episode when all three roles have
--   recorded completed results and the pure policy's episode semantics hold
--   over the frozen generation state.
--
--   parent_episode_id on this table is the IMMUTABLE PARENT LINEAGE (aihub#708
--   Batch 2A re-review blocker, mem_FHuxXIXI): on a kind='retry' row whose
--   failed_step_attempt_id names an EPISODE-BOUND invocation (an episode role
--   that recorded provider_error), the id of the episode whose role the
--   retry's replacements stand in for — the ROOT of the chain, so a retry of a
--   failed replacement inherits the same parent as its ancestor. NULL on
--   episodes and on retries of ordinary invocations. Written once at
--   authorization time and never updated: the failed history stays (results
--   are append-only), nothing rebinds, and the effective episode role lookup
--   follows the chain instead of moving rows. The parent invocation itself is
--   already named by failed_step_attempt_id (UNIQUE in
--   wi_workflow_invocations), so no second column is needed for it.

-- The current-generation pointer. steps carries the pinned flow; a legacy
-- work item keeps steps NULL / steps_version 0 forever unless a revision pins
-- a first generation.
ALTER TABLE work_items ADD COLUMN IF NOT EXISTS steps JSONB;
ALTER TABLE work_items ADD COLUMN IF NOT EXISTS steps_version INT NOT NULL DEFAULT 0 CHECK (steps_version >= 0);

-- Append-only generations. (work_item_id, steps_version) is the identity the
-- work_items pointer names; no UPDATE path exists for any column.
CREATE TABLE IF NOT EXISTS wi_workflow_generations (
    work_item_id   TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE,
    -- generation number; 1 is the first pin. Monotone per work item because
    -- the pinning transaction takes the work_items row FOR UPDATE and writes
    -- steps_version+1 in the same statement that moves the pointer.
    steps_version  INT NOT NULL CHECK (steps_version >= 1),
    -- the pinned flow: {"version":<steps_version>,"steps":[...]} with every
    -- step carrying its exact resolved skill_id and skill_version.
    steps          JSONB NOT NULL,
    -- the server-derived per-step grants, {"<step_id>":{"authority":"read_only"
    -- |"write","producer_isolation":"shared"|"independent"}}. Derived from the
    -- resolved contracts by the capability policy at pin time; a declaration,
    -- never caller input (the request has no field that reaches this).
    grants         JSONB NOT NULL,
    -- per-step semantic metadata resolved at pin time: {"<step_id>":
    -- {"capabilities":[...],"interactive":bool}}. Capabilities + runtime flag
    -- only — enough to validate a later result's review-verdict requirements
    -- without re-reading the registry, and never enough to reconstruct a
    -- skill's content.
    step_meta      JSONB NOT NULL,
    -- sha256 over the canonical (steps, grants, step_meta) triple. Lets a
    -- reader verify the generation's integrity without trusting the caller
    -- that pinned it.
    validation_digest TEXT NOT NULL CHECK (validation_digest ~ '^sha256:[0-9a-f]{64}$'),
    requires_human_session BOOLEAN NOT NULL,
    created_by     TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (work_item_id, steps_version)
);

-- Controller-minted invocations. One row per /workflow/start; step_attempt_id
-- and producer_id are server-generated and globally unique, so a forged
-- result naming either is refused on identity, not on trust.
CREATE TABLE IF NOT EXISTS wi_workflow_invocations (
    id               TEXT PRIMARY KEY,             -- winv_<8b62>
    work_item_id     TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE,
    steps_version    INT NOT NULL,
    step_id          TEXT NOT NULL,
    -- server-minted; a result must echo it exactly. UNIQUE across the table
    -- like wi_step_completions.step_attempt_id.
    step_attempt_id  TEXT NOT NULL UNIQUE,
    run_attempt_id   TEXT NOT NULL REFERENCES run_attempts(id) ON DELETE RESTRICT,
    claim_epoch      BIGINT NOT NULL,
    -- server-assigned producer identity for this invocation; never a caller
    -- string (the pure policy's producer-independence check reads it).
    producer_id      TEXT NOT NULL,
    -- the grant snapshot this invocation executes under (named
    -- invocation_grant because GRANT is a reserved SQL keyword), from the
    -- generation's grants map for this step.
    invocation_grant JSONB NOT NULL,
    -- open | recorded | superseded. recorded is set by the result that
    -- answers it; superseded is set ONLY by the explicit controller-reconcile
    -- transition (POST /v1/work_items/:id/workflow/reconcile, aihub#708 B3)
    -- when a paused/taken-over attempt's open invocations are abandoned so
    -- the live attempt can start replacements — never silently, never on the
    -- request's word (the named attempt's own row is read under the work item
    -- lock and must not be running).
    status           TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'recorded', 'superseded')),
    -- when this invocation was abandoned by the reconcile transition;
    -- NULL while open, and forever on recorded invocations.
    superseded_at    TIMESTAMPTZ,
    -- non-NULL when this invocation is one of the bounded invocations of an
    -- open repair authorization (retry of the failed attempt, or the repair /
    -- verification / review roles of an episode).
    repair_episode_id TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    recorded_at      TIMESTAMPTZ,
    CHECK (steps_version >= 1),
    -- an invocation always names its generation row: the work item's pointer
    -- can only move by inserting a NEW generation, so an old invocation's
    -- generation stays readable (append-only rule).
    FOREIGN KEY (work_item_id, steps_version)
        REFERENCES wi_workflow_generations(work_item_id, steps_version) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_wi_wf_inv_wi ON wi_workflow_invocations(work_item_id, steps_version, step_id, created_at);
CREATE INDEX IF NOT EXISTS idx_wi_wf_inv_open ON wi_workflow_invocations(work_item_id) WHERE status = 'open';

-- Replay hardening for databases migrated with an earlier draft of this
-- still-unmerged migration, whose wi_workflow_invocations had no
-- superseded_at (the reconcile transition's timestamp, aihub#708 B3): fresh
-- databases get the column from the CREATE above, replayed ones from here.
ALTER TABLE wi_workflow_invocations ADD COLUMN IF NOT EXISTS superseded_at TIMESTAMPTZ;

-- Recorded worker results, one row per terminal result. Never updated: a
-- retry records a NEW row bound to its own invocation.
CREATE TABLE IF NOT EXISTS wi_workflow_results (
    id               TEXT PRIMARY KEY,             -- wres_<8b62>
    work_item_id     TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE,
    invocation_id    TEXT NOT NULL UNIQUE REFERENCES wi_workflow_invocations(id) ON DELETE RESTRICT,
    steps_version    INT NOT NULL CHECK (steps_version >= 1),
    step_id          TEXT NOT NULL,
    -- same value as the invocation's; on the result row so the pure policy
    -- can be re-assembled from results alone.
    step_attempt_id  TEXT NOT NULL UNIQUE,
    run_attempt_id   TEXT NOT NULL REFERENCES run_attempts(id) ON DELETE RESTRICT,
    claim_epoch      BIGINT NOT NULL,
    producer_id      TEXT NOT NULL,
    status           TEXT NOT NULL CHECK (status IN ('completed', 'incomplete', 'blocked',
                                                      'provider_error', 'invalid_result')),
    review_verdict   TEXT CHECK (review_verdict IN ('pass', 'warn', 'fail')),
    -- the artifact triple the worker reported, validated for shape (id /
    -- positive version / sha256:<64 hex>, the suffix DECODED as hex) by the
    -- server before the row is written; evidence hashes get the same check.
    artifact         JSONB NOT NULL,
    evidence         JSONB NOT NULL DEFAULT '[]',
    -- the result envelope as the server accepted it, for the timeline and the
    -- controller's policy re-assembly. Immutable after insert.
    raw              JSONB NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX IF NOT EXISTS idx_wi_wf_res_wi ON wi_workflow_results(work_item_id, steps_version, step_id, created_at);

-- Human approvals. actor_user_id is the authenticated principal; the request
-- has no actor field at all. The artifact identity (work item, generation,
-- step, artifact id/version/hash) is unique and deliberately EXCLUDES the
-- decision: with the decision inside the key, an 'approved' row and a
-- 'rejected' row for the same artifact could coexist, and a check-then-insert
-- race could record both — contradictory decisions for one immutable
-- artifact (aihub#708 review blocker). With the decision outside it, the DB
-- itself permits exactly ONE decision per artifact; the approve route
-- additionally locks the work item row FOR UPDATE, serializing concurrent
-- approvals so the idempotent/conflicting answers are deterministic.
CREATE TABLE IF NOT EXISTS wi_workflow_approvals (
    id               TEXT PRIMARY KEY,             -- wapp_<8b62>
    work_item_id     TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE,
    steps_version    INT NOT NULL CHECK (steps_version >= 1),
    step_id          TEXT NOT NULL,
    artifact_id      TEXT NOT NULL,
    artifact_version INT NOT NULL CHECK (artifact_version >= 1),
    artifact_hash    TEXT NOT NULL CHECK (artifact_hash ~ '^sha256:[0-9a-f]{64}$'),
    decision         TEXT NOT NULL CHECK (decision IN ('approved', 'rejected')),
    actor_user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    actor_display    TEXT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

-- The artifact-identity key, as a unique INDEX rather than an inline table
-- constraint so the Up stays idempotent on every database shape (goose and
-- the test replay helper both re-execute this file; CREATE ... IF NOT EXISTS
-- is the one form that replays cleanly). The DROP is replay hardening for
-- databases migrated with an earlier draft of this still-unmerged migration,
-- whose auto-named key included `decision` (PostgreSQL truncates that
-- identifier to 63 bytes); fresh databases never create it.
ALTER TABLE wi_workflow_approvals
    DROP CONSTRAINT IF EXISTS wi_workflow_approvals_work_item_id_steps_version_step_id_ar_key;
CREATE UNIQUE INDEX IF NOT EXISTS wi_workflow_approvals_artifact_identity_key
    ON wi_workflow_approvals (work_item_id, steps_version, step_id,
                              artifact_id, artifact_version, artifact_hash);

CREATE INDEX IF NOT EXISTS idx_wi_wf_app_wi ON wi_workflow_approvals(work_item_id, steps_version, step_id);

-- Controller-authorized recoveries. failed_step_attempt_id is UNIQUE per kind
-- row: one authorization per failed invocation. kind mirrors the two pure
-- shapes (RepairAuthorization / RepairEpisode): retry recovers a
-- provider_error invocation ONLY (a review FAIL always takes the episode
-- path — no rerolling a gate); an episode recovers a FAIL-verdict review
-- through its three roles.
CREATE TABLE IF NOT EXISTS wi_workflow_repair_episodes (
    id                      TEXT PRIMARY KEY,      -- wrep_<8b62>
    work_item_id            TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE,
    kind                    TEXT NOT NULL CHECK (kind IN ('retry', 'episode')),
    -- the generation the failed result belongs to.
    failed_steps_version    INT NOT NULL CHECK (failed_steps_version >= 1),
    failed_step_id          TEXT NOT NULL,
    failed_step_attempt_id  TEXT NOT NULL,
    reason                  TEXT NOT NULL CHECK (length(reason) BETWEEN 10 AND 2000),
    -- the fenced attempt that opened it: the route requires the current
    -- attempt's credentials, so this is controller authorization under
    -- existing fencing, never a self-declared actor.
    run_attempt_id          TEXT NOT NULL REFERENCES run_attempts(id) ON DELETE RESTRICT,
    claim_epoch             BIGINT NOT NULL,
    authorized_by           TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    status                  TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    closed_at               TIMESTAMPTZ,
    -- the immutable parent lineage, see the file header: non-NULL only on
    -- retries that descend from an episode role invocation; names that episode.
    parent_episode_id       TEXT,
    UNIQUE (kind, failed_step_attempt_id)
);

CREATE INDEX IF NOT EXISTS idx_wi_wf_rep_wi ON wi_workflow_repair_episodes(work_item_id, status);

-- Replay hardening, the superseded_at pattern above: databases migrated with
-- an earlier draft of this still-unmerged migration (before the lineage
-- blocker fix) have no parent_episode_id; fresh databases get the column from
-- the CREATE above, replayed ones from here.
ALTER TABLE wi_workflow_repair_episodes ADD COLUMN IF NOT EXISTS parent_episode_id TEXT;
-- The effective episode role lookup scans a parent episode's descendant
-- retries, so the parent side carries its own partial index.
CREATE INDEX IF NOT EXISTS idx_wi_wf_rep_parent ON wi_workflow_repair_episodes(parent_episode_id)
    WHERE parent_episode_id IS NOT NULL;

-- +goose Down

-- 0043's Down drops the registry outright; this one does the same for the
-- workflow tables. Down is never part of a binary rollback procedure (the Up
-- is additive), and the cascade order below clears the FK graph.
DROP TABLE IF EXISTS wi_workflow_results;
DROP TABLE IF EXISTS wi_workflow_invocations;
DROP TABLE IF EXISTS wi_workflow_approvals;
DROP TABLE IF EXISTS wi_workflow_repair_episodes;
DROP TABLE IF EXISTS wi_workflow_generations;
ALTER TABLE work_items DROP COLUMN IF EXISTS steps;
ALTER TABLE work_items DROP COLUMN IF EXISTS steps_version;
