package config

import (
	"crypto/rand"
	"fmt"
	"os"
	"path/filepath"

	"github.com/pelletier/go-toml/v2"
)

// MachineConfig is loaded from ~/.polyforge/config.toml.
// It holds machine-level identity and auth credentials.
// Per design §9.5.3.
type MachineConfig struct {
	// MachineID is a stable UUID v4 for this machine.
	// Auto-generated on first pf init and never changes.
	MachineID string `toml:"machine_id"`

	Auth MachineAuth `toml:"auth"`

	// Server overrides .polyforge.yaml aihub.url (optional).
	Server *MachineServer `toml:"server,omitempty"`

	// Binary controls the polyforge CLI binary update channel (optional).
	Binary *MachineBinary `toml:"binary,omitempty"`
}

type MachineAuth struct {
	// APIKey is the raw key (use one of APIKey or APIKeyEnv, not both).
	APIKey string `toml:"api_key,omitempty"`
	// APIKeyEnv is an env-var name that holds the key.
	// Matches the .polyforge.yaml api_key_env convention.
	APIKeyEnv string `toml:"api_key_env,omitempty"`
}

type MachineServer struct {
	URL string `toml:"url"`
}

// MachineBinary controls the polyforge binary update channel.
// Set in ~/.polyforge/config.toml under [binary].
type MachineBinary struct {
	// Channel selects the bins-<channel> branch to download the binary from.
	// "dev" is the only published channel, and the default. See
	// ResolveBinaryChannel and plugins/polyforge/bin/polyforge-mcp.sh.
	Channel string `toml:"channel,omitempty"`
}

// MachineConfigDir returns ~/.polyforge.
func MachineConfigDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".polyforge")
}

// MachineConfigPath returns ~/.polyforge/config.toml.
func MachineConfigPath() string {
	return filepath.Join(MachineConfigDir(), "config.toml")
}

// LoadMachineConfig reads ~/.polyforge/config.toml.
// Returns an empty (but valid) config if the file does not exist.
func LoadMachineConfig() (*MachineConfig, error) {
	path := MachineConfigPath()
	b, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return &MachineConfig{}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var mc MachineConfig
	if err := toml.Unmarshal(b, &mc); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return &mc, nil
}

// SaveMachineConfig writes mc to ~/.polyforge/config.toml (mode 0600).
func SaveMachineConfig(mc *MachineConfig) error {
	if err := os.MkdirAll(MachineConfigDir(), 0700); err != nil {
		return fmt.Errorf("mkdir %s: %w", MachineConfigDir(), err)
	}
	b, err := toml.Marshal(mc)
	if err != nil {
		return fmt.Errorf("marshal config.toml: %w", err)
	}
	header := "# polyforge machine config — auto-generated by pf init\n" +
		"# machine_id is stable; do not edit it manually.\n\n"
	footer := "\n# The team's aihub endpoint is compiled into the polyforge binary, so this\n" +
		"# file does not need a [server] url and you should not add one just to write\n" +
		"# the address down: a copy here cannot be corrected by a release, which is how\n" +
		"# machines ended up pointing at a retired host (aihub#335). Run\n" +
		"# `polyforge doctor` to see the endpoint in use. Set this ONLY to point at a\n" +
		"# different aihub:\n" +
		"# [server]\n" +
		"# url = \"http://your-own-aihub:8080\"\n" +
		"\n# Binary update channel (optional; \"dev\" is the only published channel\n" +
		"# and the default, so you normally leave this out entirely):\n" +
		"# [binary]\n" +
		"# channel = \"dev\"\n"
	return os.WriteFile(MachineConfigPath(), append(append([]byte(header), b...), []byte(footer)...), 0600)
}

// EnsureMachineConfig loads config.toml; if it doesn't exist or has no
// machine_id, generates a fresh UUID and saves.
func EnsureMachineConfig() (*MachineConfig, error) {
	mc, err := LoadMachineConfig()
	if err != nil {
		return nil, err
	}
	if mc.MachineID == "" {
		mc.MachineID = newUUID()
		if err := SaveMachineConfig(mc); err != nil {
			return nil, err
		}
	}
	return mc, nil
}

// ResolveAPIKey returns the API key, in priority order:
//  1. POLYFORGE_API_KEY env var (highest priority — explicit override,
//     matching the `--help` contract and CLI-tool convention)
//  2. config.toml [auth] api_key
//  3. the env var named by config.toml [auth] api_key_env
func (mc *MachineConfig) ResolveAPIKey() string {
	// Global override wins (local dev key swap, CI / container env injection).
	if v := os.Getenv("POLYFORGE_API_KEY"); v != "" {
		return v
	}
	if mc.Auth.APIKey != "" {
		return mc.Auth.APIKey
	}
	if mc.Auth.APIKeyEnv != "" {
		if v := os.Getenv(mc.Auth.APIKeyEnv); v != "" {
			return v
		}
	}
	return ""
}

// ResolveBinaryChannel returns the bins-<channel> branch to fetch the polyforge
// binary from. "dev" is the only published channel and the default.
//
// aihub#305: this used to default to "stable" and pass any configured value
// through verbatim, mirroring the launcher — but bins-stable was never
// published, so both the default and a literal channel = "stable" resolved to a
// 404. The legacy value is now normalised onto dev rather than returned as-is,
// so this cannot start disagreeing with polyforge-mcp.sh's own case statement,
// which is the actual consumer of the channel today. Keep the two in step.
func (mc *MachineConfig) ResolveBinaryChannel() string {
	if mc.Binary != nil && mc.Binary.Channel != "" && mc.Binary.Channel != "stable" {
		return mc.Binary.Channel
	}
	return "dev"
}

// ResolveAihubURL returns the aihub server URL, in priority order:
//  1. POLYFORGE_AIHUB_URL env var (highest priority — explicit override,
//     matching the `--help` contract)
//  2. config.toml [server] url
//
// Returns "" if neither is set — i.e. it reports what this MACHINE was
// configured with, not what the client will end up talking to. For the latter,
// use EffectiveAihubURL; the difference is load-bearing and is explained there.
func (mc *MachineConfig) ResolveAihubURL() string {
	if v := os.Getenv("POLYFORGE_AIHUB_URL"); v != "" {
		return v
	}
	if mc.Server != nil && mc.Server.URL != "" {
		return mc.Server.URL
	}
	return ""
}

// AihubURLDefault is the team's shared aihub endpoint, compiled into the
// polyforge binary. It is the ONE place a polyforge client reads the address
// from, and the only copy of it a change has to touch.
//
// aihub#335: this string used to be transcribed by hand. docs/onboarding.md
// step 2 held a heredoc that every newcomer pasted into
// ~/.polyforge/config.toml, and thirteen other files carried one of the two
// addresses too (24 occurrences at e8fbfcb; most are historical records that
// are correct as written — see internal/cli/onboarding_address_test.go for the
// classification) — while the host it names moves. docs/deployment.md records
// the server moving from 10.146.0.16 to 10.146.0.34, and notes that the current
// host's public IP changes across stop/start. So a copy taken before a move
// points at a dead
// address, and the newcomer reads the resulting timeout as a bad API key
// (aihub#331 was that exact debugging session). A document cannot be corrected
// on the machines that already copied it; a constant in the binary can be, and
// is — the plugin launcher refreshes the binary from bins-dev daily, so a change
// here reaches every machine within a day of landing on main without anyone
// editing a config file.
//
// Both higher-priority layers still win, so running your own aihub needs no
// change to this constant (see EffectiveAihubURL):
//
//	POLYFORGE_AIHUB_URL=http://host:8080   one-shot, CI, containers
//	[server] url = "http://host:8080"      in ~/.polyforge/config.toml
//
// docs/deployment.md's "Current production" table names the same host for an
// unrelated reason — which VM an operator SSHes into to run a deploy — and is
// read by no client. Do not turn this constant into a pointer at that table, or
// that table into a pointer at this constant: they answer different questions
// and only happen to agree today.
const AihubURLDefault = "http://10.146.0.34:8080"

// EffectiveAihubURL resolves the endpoint a polyforge client actually talks to,
// and names the layer that supplied it so `polyforge doctor` can print both.
// Priority:
//
//  1. POLYFORGE_AIHUB_URL
//  2. ~/.polyforge/config.toml [server] url
//  3. workspaceURL — .polyforge.yaml aihub.url, passed in by the caller
//  4. AihubURLDefault
//
// It never returns "". Before aihub#335 an unconfigured machine got an empty
// base URL: the MCP server started anyway and every request failed on a URL
// with no host, and `polyforge init` reached client.WhoAmI on a nil client.
//
// Deliberately NOT folded into ResolveAihubURL, which still reports "" when
// this machine configured nothing. That distinction has a consumer:
// writePolyforgeYAML copies ResolveAihubURL's result into .polyforge.yaml, and
// writing the built-in default there would pin that workspace to today's
// address in a file no release can update — reintroducing the stale-copy defect
// this constant exists to remove, one copy per workspace instead of per
// document. Callers that want an endpoint to CONNECT to want this function;
// callers that PERSIST what they were told want ResolveAihubURL.
func EffectiveAihubURL(mc *MachineConfig, workspaceURL string) (url, source string) {
	if v := os.Getenv("POLYFORGE_AIHUB_URL"); v != "" {
		return v, "POLYFORGE_AIHUB_URL"
	}
	if mc != nil && mc.Server != nil && mc.Server.URL != "" {
		return mc.Server.URL, "~/.polyforge/config.toml [server] url"
	}
	if workspaceURL != "" {
		return workspaceURL, ".polyforge.yaml aihub.url"
	}
	return AihubURLDefault, "built-in default"
}

func newUUID() string {
	var b [16]byte
	rand.Read(b[:]) //nolint:errcheck
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}
