package config

import (
	"crypto/rand"
	"fmt"
	"os"
	"path/filepath"

	"github.com/pelletier/go-toml/v2"
)

// MachineConfig is loaded from ~/.polyforge/config.toml.
// It holds machine-level identity and auth credentials.
// Per design §9.5.3.
type MachineConfig struct {
	// MachineID is a stable UUID v4 for this machine.
	// Auto-generated on first pf init and never changes.
	MachineID string `toml:"machine_id"`

	Auth MachineAuth `toml:"auth"`

	// Server overrides .polyforge.yaml aihub.url (optional).
	Server *MachineServer `toml:"server,omitempty"`

	// Binary controls the polyforge CLI binary update channel (optional).
	Binary *MachineBinary `toml:"binary,omitempty"`
}

type MachineAuth struct {
	// APIKey is the raw key (use one of APIKey or APIKeyEnv, not both).
	APIKey string `toml:"api_key,omitempty"`
	// APIKeyEnv is an env-var name that holds the key.
	// Matches the .polyforge.yaml api_key_env convention.
	APIKeyEnv string `toml:"api_key_env,omitempty"`
}

type MachineServer struct {
	URL string `toml:"url"`
}

// MachineBinary controls the polyforge binary update channel.
// Set in ~/.polyforge/config.toml under [binary].
type MachineBinary struct {
	// Channel is "stable" (default) or "dev" (pre-release builds).
	Channel string `toml:"channel,omitempty"`
}

// MachineConfigDir returns ~/.polyforge.
func MachineConfigDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".polyforge")
}

// MachineConfigPath returns ~/.polyforge/config.toml.
func MachineConfigPath() string {
	return filepath.Join(MachineConfigDir(), "config.toml")
}

// LoadMachineConfig reads ~/.polyforge/config.toml.
// Returns an empty (but valid) config if the file does not exist.
func LoadMachineConfig() (*MachineConfig, error) {
	path := MachineConfigPath()
	b, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return &MachineConfig{}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var mc MachineConfig
	if err := toml.Unmarshal(b, &mc); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return &mc, nil
}

// SaveMachineConfig writes mc to ~/.polyforge/config.toml (mode 0600).
func SaveMachineConfig(mc *MachineConfig) error {
	if err := os.MkdirAll(MachineConfigDir(), 0700); err != nil {
		return fmt.Errorf("mkdir %s: %w", MachineConfigDir(), err)
	}
	b, err := toml.Marshal(mc)
	if err != nil {
		return fmt.Errorf("marshal config.toml: %w", err)
	}
	header := "# polyforge machine config — auto-generated by pf init\n" +
		"# machine_id is stable; do not edit it manually.\n\n"
	footer := "\n# Binary update channel (optional; default: stable):\n" +
		"# [binary]\n" +
		"# channel = \"stable\"   # stable | dev\n"
	return os.WriteFile(MachineConfigPath(), append(append([]byte(header), b...), []byte(footer)...), 0600)
}

// EnsureMachineConfig loads config.toml; if it doesn't exist or has no
// machine_id, generates a fresh UUID and saves.
func EnsureMachineConfig() (*MachineConfig, error) {
	mc, err := LoadMachineConfig()
	if err != nil {
		return nil, err
	}
	if mc.MachineID == "" {
		mc.MachineID = newUUID()
		if err := SaveMachineConfig(mc); err != nil {
			return nil, err
		}
	}
	return mc, nil
}

// ResolveAPIKey returns the API key from mc, consulting APIKeyEnv if APIKey
// is empty. Falls back to the POLYFORGE_API_KEY env var last.
func (mc *MachineConfig) ResolveAPIKey() string {
	if mc.Auth.APIKey != "" {
		return mc.Auth.APIKey
	}
	if mc.Auth.APIKeyEnv != "" {
		if v := os.Getenv(mc.Auth.APIKeyEnv); v != "" {
			return v
		}
	}
	// Global fallback (CI / override)
	return os.Getenv("POLYFORGE_API_KEY")
}

// ResolveBinaryChannel returns the configured binary channel ("stable" or "dev").
// Falls back to "stable" if not configured.
func (mc *MachineConfig) ResolveBinaryChannel() string {
	if mc.Binary != nil && mc.Binary.Channel != "" {
		return mc.Binary.Channel
	}
	return "stable"
}

// ResolveAihubURL returns the server URL from mc, or "" if not set.
func (mc *MachineConfig) ResolveAihubURL() string {
	if mc.Server != nil && mc.Server.URL != "" {
		return mc.Server.URL
	}
	return os.Getenv("POLYFORGE_AIHUB_URL")
}

func newUUID() string {
	var b [16]byte
	rand.Read(b[:]) //nolint:errcheck
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}
